/* Generated by Yosys 0.53 (git sha1 53c22ab7c0ced80861c7536c5dae682c30fb5834, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module tc(clk, rst_n, a_in, b_in, c_in, d1_in, d2_in, y_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  input a_in;
  wire a_in;
  input b_in;
  wire b_in;
  input c_in;
  wire c_in;
  input clk;
  wire clk;
  input d1_in;
  wire d1_in;
  input d2_in;
  wire d2_in;
  input rst_n;
  wire rst_n;
  wire sop_0;
  output y_out;
  wire y_out;
  INV_X1 _06_ (
    .A(d1_in),
    .ZN(_02_)
  );
  INV_X1 _07_ (
    .A(b_in),
    .ZN(_03_)
  );
  INV_X1 _08_ (
    .A(d2_in),
    .ZN(_04_)
  );
  OR2_X1 _09_ (
    .A1(b_in),
    .A2(a_in),
    .ZN(_00_)
  );
  NAND2_X1 _10_ (
    .A1(c_in),
    .A2(a_in),
    .ZN(_01_)
  );
  OAI33_X1 _11_ (
    .A1(c_in),
    .A2(_04_),
    .A3(_00_),
    .B1(_01_),
    .B2(_03_),
    .B3(_02_),
    .ZN(sop_0)
  );
  DFFR_X1 _12_ (
    .CK(clk),
    .D(sop_0),
    .Q(y_out),
    .QN(_05_),
    .RN(rst_n)
  );
endmodule
