/* Generated by Yosys 0.53 (git sha1 53c22ab7c0ced80861c7536c5dae682c30fb5834, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module tc(clk, rst_n, a_in, b_in, salt_in, y_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  input [31:0] a_in;
  wire [31:0] a_in;
  wire [31:0] a_q;
  input [31:0] b_in;
  wire [31:0] b_in;
  wire [31:0] b_q;
  input clk;
  wire clk;
  wire cmp_eq;
  input rst_n;
  wire rst_n;
  input [31:0] salt_in;
  wire [31:0] salt_in;
  wire [31:0] salt_q;
  output y_out;
  wire y_out;
  MUX2_X1 _203_ (
    .A(salt_q[11]),
    .B(_005_),
    .S(b_q[11]),
    .Z(_016_)
  );
  MUX2_X1 _204_ (
    .A(salt_q[10]),
    .B(salt_q[11]),
    .S(a_q[11]),
    .Z(_017_)
  );
  XOR2_X1 _205_ (
    .A(_016_),
    .B(_017_),
    .Z(_018_)
  );
  MUX2_X1 _206_ (
    .A(salt_q[9]),
    .B(_004_),
    .S(b_q[9]),
    .Z(_019_)
  );
  MUX2_X1 _207_ (
    .A(salt_q[8]),
    .B(salt_q[9]),
    .S(a_q[9]),
    .Z(_020_)
  );
  XOR2_X1 _208_ (
    .A(_019_),
    .B(_020_),
    .Z(_021_)
  );
  MUX2_X1 _209_ (
    .A(salt_q[13]),
    .B(_006_),
    .S(b_q[13]),
    .Z(_022_)
  );
  MUX2_X1 _210_ (
    .A(salt_q[12]),
    .B(salt_q[13]),
    .S(a_q[13]),
    .Z(_023_)
  );
  XOR2_X1 _211_ (
    .A(_022_),
    .B(_023_),
    .Z(_024_)
  );
  MUX2_X1 _212_ (
    .A(_000_),
    .B(salt_q[3]),
    .S(b_q[2]),
    .Z(_025_)
  );
  MUX2_X1 _213_ (
    .A(salt_q[1]),
    .B(salt_q[2]),
    .S(a_q[2]),
    .Z(_026_)
  );
  XNOR2_X1 _214_ (
    .A(_025_),
    .B(_026_),
    .ZN(_027_)
  );
  NOR4_X1 _215_ (
    .A1(_018_),
    .A2(_021_),
    .A3(_024_),
    .A4(_027_),
    .ZN(_028_)
  );
  MUX2_X1 _216_ (
    .A(_001_),
    .B(salt_q[5]),
    .S(b_q[4]),
    .Z(_029_)
  );
  MUX2_X1 _217_ (
    .A(salt_q[3]),
    .B(salt_q[4]),
    .S(a_q[4]),
    .Z(_030_)
  );
  XNOR2_X1 _218_ (
    .A(_029_),
    .B(_030_),
    .ZN(_031_)
  );
  MUX2_X1 _219_ (
    .A(_006_),
    .B(salt_q[15]),
    .S(b_q[14]),
    .Z(_032_)
  );
  MUX2_X1 _220_ (
    .A(salt_q[13]),
    .B(salt_q[14]),
    .S(a_q[14]),
    .Z(_033_)
  );
  XNOR2_X1 _221_ (
    .A(_032_),
    .B(_033_),
    .ZN(_034_)
  );
  MUX2_X1 _222_ (
    .A(_004_),
    .B(salt_q[11]),
    .S(b_q[10]),
    .Z(_035_)
  );
  MUX2_X1 _223_ (
    .A(salt_q[9]),
    .B(salt_q[10]),
    .S(a_q[10]),
    .Z(_036_)
  );
  XNOR2_X1 _224_ (
    .A(_035_),
    .B(_036_),
    .ZN(_037_)
  );
  MUX2_X1 _225_ (
    .A(salt_q[31]),
    .B(_015_),
    .S(b_q[31]),
    .Z(_038_)
  );
  MUX2_X1 _226_ (
    .A(salt_q[30]),
    .B(salt_q[31]),
    .S(a_q[31]),
    .Z(_039_)
  );
  XOR2_X1 _227_ (
    .A(_038_),
    .B(_039_),
    .Z(_040_)
  );
  NOR4_X1 _228_ (
    .A1(_031_),
    .A2(_034_),
    .A3(_037_),
    .A4(_040_),
    .ZN(_041_)
  );
  MUX2_X1 _229_ (
    .A(salt_q[1]),
    .B(_000_),
    .S(b_q[1]),
    .Z(_042_)
  );
  MUX2_X1 _230_ (
    .A(salt_q[0]),
    .B(salt_q[1]),
    .S(a_q[1]),
    .Z(_043_)
  );
  XOR2_X1 _231_ (
    .A(_042_),
    .B(_043_),
    .Z(_044_)
  );
  MUX2_X1 _232_ (
    .A(_013_),
    .B(salt_q[29]),
    .S(b_q[28]),
    .Z(_045_)
  );
  MUX2_X1 _233_ (
    .A(salt_q[27]),
    .B(salt_q[28]),
    .S(a_q[28]),
    .Z(_046_)
  );
  XNOR2_X1 _234_ (
    .A(_045_),
    .B(_046_),
    .ZN(_047_)
  );
  MUX2_X1 _235_ (
    .A(salt_q[5]),
    .B(_002_),
    .S(b_q[5]),
    .Z(_048_)
  );
  MUX2_X1 _236_ (
    .A(salt_q[4]),
    .B(salt_q[5]),
    .S(a_q[5]),
    .Z(_049_)
  );
  XOR2_X1 _237_ (
    .A(_048_),
    .B(_049_),
    .Z(_050_)
  );
  MUX2_X1 _238_ (
    .A(salt_q[7]),
    .B(_003_),
    .S(b_q[7]),
    .Z(_051_)
  );
  MUX2_X1 _239_ (
    .A(salt_q[6]),
    .B(salt_q[7]),
    .S(a_q[7]),
    .Z(_052_)
  );
  XOR2_X1 _240_ (
    .A(_051_),
    .B(_052_),
    .Z(_053_)
  );
  NOR4_X1 _241_ (
    .A1(_044_),
    .A2(_047_),
    .A3(_050_),
    .A4(_053_),
    .ZN(_054_)
  );
  MUX2_X1 _242_ (
    .A(_010_),
    .B(salt_q[23]),
    .S(b_q[22]),
    .Z(_055_)
  );
  MUX2_X1 _243_ (
    .A(salt_q[21]),
    .B(salt_q[22]),
    .S(a_q[22]),
    .Z(_056_)
  );
  XNOR2_X1 _244_ (
    .A(_055_),
    .B(_056_),
    .ZN(_057_)
  );
  MUX2_X1 _245_ (
    .A(_011_),
    .B(salt_q[25]),
    .S(b_q[24]),
    .Z(_058_)
  );
  MUX2_X1 _246_ (
    .A(salt_q[23]),
    .B(salt_q[24]),
    .S(a_q[24]),
    .Z(_059_)
  );
  XNOR2_X1 _247_ (
    .A(_058_),
    .B(_059_),
    .ZN(_060_)
  );
  MUX2_X1 _248_ (
    .A(_008_),
    .B(salt_q[19]),
    .S(b_q[18]),
    .Z(_061_)
  );
  MUX2_X1 _249_ (
    .A(salt_q[17]),
    .B(salt_q[18]),
    .S(a_q[18]),
    .Z(_062_)
  );
  XNOR2_X1 _250_ (
    .A(_061_),
    .B(_062_),
    .ZN(_063_)
  );
  MUX2_X1 _251_ (
    .A(_012_),
    .B(salt_q[27]),
    .S(b_q[26]),
    .Z(_064_)
  );
  MUX2_X1 _252_ (
    .A(salt_q[25]),
    .B(salt_q[26]),
    .S(a_q[26]),
    .Z(_065_)
  );
  XNOR2_X1 _253_ (
    .A(_064_),
    .B(_065_),
    .ZN(_066_)
  );
  NOR4_X1 _254_ (
    .A1(_057_),
    .A2(_060_),
    .A3(_063_),
    .A4(_066_),
    .ZN(_067_)
  );
  NAND4_X1 _255_ (
    .A1(_028_),
    .A2(_041_),
    .A3(_054_),
    .A4(_067_),
    .ZN(_068_)
  );
  MUX2_X1 _256_ (
    .A(_015_),
    .B(salt_q[1]),
    .S(b_q[0]),
    .Z(_069_)
  );
  MUX2_X1 _257_ (
    .A(salt_q[31]),
    .B(salt_q[0]),
    .S(a_q[0]),
    .Z(_070_)
  );
  XNOR2_X1 _258_ (
    .A(_069_),
    .B(_070_),
    .ZN(_071_)
  );
  MUX2_X1 _259_ (
    .A(_007_),
    .B(salt_q[17]),
    .S(b_q[16]),
    .Z(_072_)
  );
  MUX2_X1 _260_ (
    .A(salt_q[15]),
    .B(salt_q[16]),
    .S(a_q[16]),
    .Z(_073_)
  );
  XNOR2_X1 _261_ (
    .A(_072_),
    .B(_073_),
    .ZN(_074_)
  );
  MUX2_X1 _262_ (
    .A(_014_),
    .B(salt_q[31]),
    .S(b_q[30]),
    .Z(_075_)
  );
  MUX2_X1 _263_ (
    .A(salt_q[29]),
    .B(salt_q[30]),
    .S(a_q[30]),
    .Z(_076_)
  );
  XNOR2_X1 _264_ (
    .A(_075_),
    .B(_076_),
    .ZN(_077_)
  );
  MUX2_X1 _265_ (
    .A(_003_),
    .B(salt_q[9]),
    .S(b_q[8]),
    .Z(_078_)
  );
  MUX2_X1 _266_ (
    .A(salt_q[7]),
    .B(salt_q[8]),
    .S(a_q[8]),
    .Z(_079_)
  );
  XNOR2_X1 _267_ (
    .A(_078_),
    .B(_079_),
    .ZN(_080_)
  );
  NOR4_X1 _268_ (
    .A1(_071_),
    .A2(_074_),
    .A3(_077_),
    .A4(_080_),
    .ZN(_081_)
  );
  MUX2_X1 _269_ (
    .A(salt_q[25]),
    .B(_012_),
    .S(b_q[25]),
    .Z(_082_)
  );
  MUX2_X1 _270_ (
    .A(salt_q[24]),
    .B(salt_q[25]),
    .S(a_q[25]),
    .Z(_083_)
  );
  XOR2_X1 _271_ (
    .A(_082_),
    .B(_083_),
    .Z(_084_)
  );
  MUX2_X1 _272_ (
    .A(salt_q[27]),
    .B(_013_),
    .S(b_q[27]),
    .Z(_085_)
  );
  MUX2_X1 _273_ (
    .A(salt_q[26]),
    .B(salt_q[27]),
    .S(a_q[27]),
    .Z(_086_)
  );
  XOR2_X1 _274_ (
    .A(_085_),
    .B(_086_),
    .Z(_087_)
  );
  MUX2_X1 _275_ (
    .A(salt_q[3]),
    .B(_001_),
    .S(b_q[3]),
    .Z(_088_)
  );
  MUX2_X1 _276_ (
    .A(salt_q[2]),
    .B(salt_q[3]),
    .S(a_q[3]),
    .Z(_089_)
  );
  XOR2_X1 _277_ (
    .A(_088_),
    .B(_089_),
    .Z(_090_)
  );
  MUX2_X1 _278_ (
    .A(_005_),
    .B(salt_q[13]),
    .S(b_q[12]),
    .Z(_091_)
  );
  MUX2_X1 _279_ (
    .A(salt_q[11]),
    .B(salt_q[12]),
    .S(a_q[12]),
    .Z(_092_)
  );
  XNOR2_X1 _280_ (
    .A(_091_),
    .B(_092_),
    .ZN(_093_)
  );
  NOR4_X1 _281_ (
    .A1(_084_),
    .A2(_087_),
    .A3(_090_),
    .A4(_093_),
    .ZN(_094_)
  );
  MUX2_X1 _282_ (
    .A(_009_),
    .B(salt_q[21]),
    .S(b_q[20]),
    .Z(_095_)
  );
  MUX2_X1 _283_ (
    .A(salt_q[19]),
    .B(salt_q[20]),
    .S(a_q[20]),
    .Z(_096_)
  );
  XNOR2_X1 _284_ (
    .A(_095_),
    .B(_096_),
    .ZN(_097_)
  );
  MUX2_X1 _285_ (
    .A(salt_q[19]),
    .B(_009_),
    .S(b_q[19]),
    .Z(_098_)
  );
  MUX2_X1 _286_ (
    .A(salt_q[18]),
    .B(salt_q[19]),
    .S(a_q[19]),
    .Z(_099_)
  );
  XOR2_X1 _287_ (
    .A(_098_),
    .B(_099_),
    .Z(_100_)
  );
  MUX2_X1 _288_ (
    .A(salt_q[15]),
    .B(_007_),
    .S(b_q[15]),
    .Z(_101_)
  );
  MUX2_X1 _289_ (
    .A(salt_q[14]),
    .B(salt_q[15]),
    .S(a_q[15]),
    .Z(_102_)
  );
  XOR2_X1 _290_ (
    .A(_101_),
    .B(_102_),
    .Z(_103_)
  );
  MUX2_X1 _291_ (
    .A(_002_),
    .B(salt_q[7]),
    .S(b_q[6]),
    .Z(_104_)
  );
  MUX2_X1 _292_ (
    .A(salt_q[5]),
    .B(salt_q[6]),
    .S(a_q[6]),
    .Z(_105_)
  );
  XNOR2_X1 _293_ (
    .A(_104_),
    .B(_105_),
    .ZN(_106_)
  );
  NOR4_X1 _294_ (
    .A1(_097_),
    .A2(_100_),
    .A3(_103_),
    .A4(_106_),
    .ZN(_107_)
  );
  MUX2_X1 _295_ (
    .A(salt_q[29]),
    .B(_014_),
    .S(b_q[29]),
    .Z(_108_)
  );
  MUX2_X1 _296_ (
    .A(salt_q[28]),
    .B(salt_q[29]),
    .S(a_q[29]),
    .Z(_109_)
  );
  XOR2_X1 _297_ (
    .A(_108_),
    .B(_109_),
    .Z(_110_)
  );
  MUX2_X1 _298_ (
    .A(salt_q[23]),
    .B(_011_),
    .S(b_q[23]),
    .Z(_111_)
  );
  MUX2_X1 _299_ (
    .A(salt_q[22]),
    .B(salt_q[23]),
    .S(a_q[23]),
    .Z(_112_)
  );
  XOR2_X1 _300_ (
    .A(_111_),
    .B(_112_),
    .Z(_113_)
  );
  MUX2_X1 _301_ (
    .A(salt_q[17]),
    .B(_008_),
    .S(b_q[17]),
    .Z(_114_)
  );
  MUX2_X1 _302_ (
    .A(salt_q[16]),
    .B(salt_q[17]),
    .S(a_q[17]),
    .Z(_115_)
  );
  XOR2_X1 _303_ (
    .A(_114_),
    .B(_115_),
    .Z(_116_)
  );
  MUX2_X1 _304_ (
    .A(salt_q[21]),
    .B(_010_),
    .S(b_q[21]),
    .Z(_117_)
  );
  MUX2_X1 _305_ (
    .A(salt_q[20]),
    .B(salt_q[21]),
    .S(a_q[21]),
    .Z(_118_)
  );
  XOR2_X1 _306_ (
    .A(_117_),
    .B(_118_),
    .Z(_119_)
  );
  NOR4_X1 _307_ (
    .A1(_110_),
    .A2(_113_),
    .A3(_116_),
    .A4(_119_),
    .ZN(_120_)
  );
  NAND4_X1 _308_ (
    .A1(_081_),
    .A2(_094_),
    .A3(_107_),
    .A4(_120_),
    .ZN(_121_)
  );
  NOR2_X1 _309_ (
    .A1(_068_),
    .A2(_121_),
    .ZN(cmp_eq)
  );
  DFFR_X1 _310_ (
    .CK(clk),
    .D(cmp_eq),
    .Q(y_out),
    .QN(_123_),
    .RN(rst_n)
  );
  DFFR_X1 _311_ (
    .CK(clk),
    .D(a_in[0]),
    .Q(a_q[0]),
    .QN(_124_),
    .RN(rst_n)
  );
  DFFR_X1 _312_ (
    .CK(clk),
    .D(a_in[1]),
    .Q(a_q[1]),
    .QN(_125_),
    .RN(rst_n)
  );
  DFFR_X1 _313_ (
    .CK(clk),
    .D(a_in[2]),
    .Q(a_q[2]),
    .QN(_126_),
    .RN(rst_n)
  );
  DFFR_X1 _314_ (
    .CK(clk),
    .D(a_in[3]),
    .Q(a_q[3]),
    .QN(_127_),
    .RN(rst_n)
  );
  DFFR_X1 _315_ (
    .CK(clk),
    .D(a_in[4]),
    .Q(a_q[4]),
    .QN(_128_),
    .RN(rst_n)
  );
  DFFR_X1 _316_ (
    .CK(clk),
    .D(a_in[5]),
    .Q(a_q[5]),
    .QN(_129_),
    .RN(rst_n)
  );
  DFFR_X1 _317_ (
    .CK(clk),
    .D(a_in[6]),
    .Q(a_q[6]),
    .QN(_130_),
    .RN(rst_n)
  );
  DFFR_X1 _318_ (
    .CK(clk),
    .D(a_in[7]),
    .Q(a_q[7]),
    .QN(_131_),
    .RN(rst_n)
  );
  DFFR_X1 _319_ (
    .CK(clk),
    .D(a_in[8]),
    .Q(a_q[8]),
    .QN(_132_),
    .RN(rst_n)
  );
  DFFR_X1 _320_ (
    .CK(clk),
    .D(a_in[9]),
    .Q(a_q[9]),
    .QN(_133_),
    .RN(rst_n)
  );
  DFFR_X1 _321_ (
    .CK(clk),
    .D(a_in[10]),
    .Q(a_q[10]),
    .QN(_134_),
    .RN(rst_n)
  );
  DFFR_X1 _322_ (
    .CK(clk),
    .D(a_in[11]),
    .Q(a_q[11]),
    .QN(_135_),
    .RN(rst_n)
  );
  DFFR_X1 _323_ (
    .CK(clk),
    .D(a_in[12]),
    .Q(a_q[12]),
    .QN(_136_),
    .RN(rst_n)
  );
  DFFR_X1 _324_ (
    .CK(clk),
    .D(a_in[13]),
    .Q(a_q[13]),
    .QN(_137_),
    .RN(rst_n)
  );
  DFFR_X1 _325_ (
    .CK(clk),
    .D(a_in[14]),
    .Q(a_q[14]),
    .QN(_138_),
    .RN(rst_n)
  );
  DFFR_X1 _326_ (
    .CK(clk),
    .D(a_in[15]),
    .Q(a_q[15]),
    .QN(_139_),
    .RN(rst_n)
  );
  DFFR_X1 _327_ (
    .CK(clk),
    .D(a_in[16]),
    .Q(a_q[16]),
    .QN(_140_),
    .RN(rst_n)
  );
  DFFR_X1 _328_ (
    .CK(clk),
    .D(a_in[17]),
    .Q(a_q[17]),
    .QN(_141_),
    .RN(rst_n)
  );
  DFFR_X1 _329_ (
    .CK(clk),
    .D(a_in[18]),
    .Q(a_q[18]),
    .QN(_142_),
    .RN(rst_n)
  );
  DFFR_X1 _330_ (
    .CK(clk),
    .D(a_in[19]),
    .Q(a_q[19]),
    .QN(_143_),
    .RN(rst_n)
  );
  DFFR_X1 _331_ (
    .CK(clk),
    .D(a_in[20]),
    .Q(a_q[20]),
    .QN(_144_),
    .RN(rst_n)
  );
  DFFR_X1 _332_ (
    .CK(clk),
    .D(a_in[21]),
    .Q(a_q[21]),
    .QN(_145_),
    .RN(rst_n)
  );
  DFFR_X1 _333_ (
    .CK(clk),
    .D(a_in[22]),
    .Q(a_q[22]),
    .QN(_146_),
    .RN(rst_n)
  );
  DFFR_X1 _334_ (
    .CK(clk),
    .D(a_in[23]),
    .Q(a_q[23]),
    .QN(_147_),
    .RN(rst_n)
  );
  DFFR_X1 _335_ (
    .CK(clk),
    .D(a_in[24]),
    .Q(a_q[24]),
    .QN(_148_),
    .RN(rst_n)
  );
  DFFR_X1 _336_ (
    .CK(clk),
    .D(a_in[25]),
    .Q(a_q[25]),
    .QN(_149_),
    .RN(rst_n)
  );
  DFFR_X1 _337_ (
    .CK(clk),
    .D(a_in[26]),
    .Q(a_q[26]),
    .QN(_150_),
    .RN(rst_n)
  );
  DFFR_X1 _338_ (
    .CK(clk),
    .D(a_in[27]),
    .Q(a_q[27]),
    .QN(_151_),
    .RN(rst_n)
  );
  DFFR_X1 _339_ (
    .CK(clk),
    .D(a_in[28]),
    .Q(a_q[28]),
    .QN(_152_),
    .RN(rst_n)
  );
  DFFR_X1 _340_ (
    .CK(clk),
    .D(a_in[29]),
    .Q(a_q[29]),
    .QN(_153_),
    .RN(rst_n)
  );
  DFFR_X1 _341_ (
    .CK(clk),
    .D(a_in[30]),
    .Q(a_q[30]),
    .QN(_154_),
    .RN(rst_n)
  );
  DFFR_X1 _342_ (
    .CK(clk),
    .D(a_in[31]),
    .Q(a_q[31]),
    .QN(_155_),
    .RN(rst_n)
  );
  DFFR_X1 _343_ (
    .CK(clk),
    .D(b_in[0]),
    .Q(b_q[0]),
    .QN(_156_),
    .RN(rst_n)
  );
  DFFR_X1 _344_ (
    .CK(clk),
    .D(b_in[1]),
    .Q(b_q[1]),
    .QN(_157_),
    .RN(rst_n)
  );
  DFFR_X1 _345_ (
    .CK(clk),
    .D(b_in[2]),
    .Q(b_q[2]),
    .QN(_158_),
    .RN(rst_n)
  );
  DFFR_X1 _346_ (
    .CK(clk),
    .D(b_in[3]),
    .Q(b_q[3]),
    .QN(_159_),
    .RN(rst_n)
  );
  DFFR_X1 _347_ (
    .CK(clk),
    .D(b_in[4]),
    .Q(b_q[4]),
    .QN(_160_),
    .RN(rst_n)
  );
  DFFR_X1 _348_ (
    .CK(clk),
    .D(b_in[5]),
    .Q(b_q[5]),
    .QN(_161_),
    .RN(rst_n)
  );
  DFFR_X1 _349_ (
    .CK(clk),
    .D(b_in[6]),
    .Q(b_q[6]),
    .QN(_162_),
    .RN(rst_n)
  );
  DFFR_X1 _350_ (
    .CK(clk),
    .D(b_in[7]),
    .Q(b_q[7]),
    .QN(_163_),
    .RN(rst_n)
  );
  DFFR_X1 _351_ (
    .CK(clk),
    .D(b_in[8]),
    .Q(b_q[8]),
    .QN(_164_),
    .RN(rst_n)
  );
  DFFR_X1 _352_ (
    .CK(clk),
    .D(b_in[9]),
    .Q(b_q[9]),
    .QN(_165_),
    .RN(rst_n)
  );
  DFFR_X1 _353_ (
    .CK(clk),
    .D(b_in[10]),
    .Q(b_q[10]),
    .QN(_166_),
    .RN(rst_n)
  );
  DFFR_X1 _354_ (
    .CK(clk),
    .D(b_in[11]),
    .Q(b_q[11]),
    .QN(_167_),
    .RN(rst_n)
  );
  DFFR_X1 _355_ (
    .CK(clk),
    .D(b_in[12]),
    .Q(b_q[12]),
    .QN(_168_),
    .RN(rst_n)
  );
  DFFR_X1 _356_ (
    .CK(clk),
    .D(b_in[13]),
    .Q(b_q[13]),
    .QN(_169_),
    .RN(rst_n)
  );
  DFFR_X1 _357_ (
    .CK(clk),
    .D(b_in[14]),
    .Q(b_q[14]),
    .QN(_170_),
    .RN(rst_n)
  );
  DFFR_X1 _358_ (
    .CK(clk),
    .D(b_in[15]),
    .Q(b_q[15]),
    .QN(_171_),
    .RN(rst_n)
  );
  DFFR_X1 _359_ (
    .CK(clk),
    .D(b_in[16]),
    .Q(b_q[16]),
    .QN(_172_),
    .RN(rst_n)
  );
  DFFR_X1 _360_ (
    .CK(clk),
    .D(b_in[17]),
    .Q(b_q[17]),
    .QN(_173_),
    .RN(rst_n)
  );
  DFFR_X1 _361_ (
    .CK(clk),
    .D(b_in[18]),
    .Q(b_q[18]),
    .QN(_174_),
    .RN(rst_n)
  );
  DFFR_X1 _362_ (
    .CK(clk),
    .D(b_in[19]),
    .Q(b_q[19]),
    .QN(_175_),
    .RN(rst_n)
  );
  DFFR_X1 _363_ (
    .CK(clk),
    .D(b_in[20]),
    .Q(b_q[20]),
    .QN(_176_),
    .RN(rst_n)
  );
  DFFR_X1 _364_ (
    .CK(clk),
    .D(b_in[21]),
    .Q(b_q[21]),
    .QN(_177_),
    .RN(rst_n)
  );
  DFFR_X1 _365_ (
    .CK(clk),
    .D(b_in[22]),
    .Q(b_q[22]),
    .QN(_178_),
    .RN(rst_n)
  );
  DFFR_X1 _366_ (
    .CK(clk),
    .D(b_in[23]),
    .Q(b_q[23]),
    .QN(_179_),
    .RN(rst_n)
  );
  DFFR_X1 _367_ (
    .CK(clk),
    .D(b_in[24]),
    .Q(b_q[24]),
    .QN(_180_),
    .RN(rst_n)
  );
  DFFR_X1 _368_ (
    .CK(clk),
    .D(b_in[25]),
    .Q(b_q[25]),
    .QN(_181_),
    .RN(rst_n)
  );
  DFFR_X1 _369_ (
    .CK(clk),
    .D(b_in[26]),
    .Q(b_q[26]),
    .QN(_182_),
    .RN(rst_n)
  );
  DFFR_X1 _370_ (
    .CK(clk),
    .D(b_in[27]),
    .Q(b_q[27]),
    .QN(_183_),
    .RN(rst_n)
  );
  DFFR_X1 _371_ (
    .CK(clk),
    .D(b_in[28]),
    .Q(b_q[28]),
    .QN(_184_),
    .RN(rst_n)
  );
  DFFR_X1 _372_ (
    .CK(clk),
    .D(b_in[29]),
    .Q(b_q[29]),
    .QN(_185_),
    .RN(rst_n)
  );
  DFFR_X1 _373_ (
    .CK(clk),
    .D(b_in[30]),
    .Q(b_q[30]),
    .QN(_186_),
    .RN(rst_n)
  );
  DFFR_X1 _374_ (
    .CK(clk),
    .D(b_in[31]),
    .Q(b_q[31]),
    .QN(_187_),
    .RN(rst_n)
  );
  DFFR_X1 _375_ (
    .CK(clk),
    .D(salt_in[0]),
    .Q(salt_q[0]),
    .QN(_015_),
    .RN(rst_n)
  );
  DFFR_X1 _376_ (
    .CK(clk),
    .D(salt_in[1]),
    .Q(salt_q[1]),
    .QN(_188_),
    .RN(rst_n)
  );
  DFFR_X1 _377_ (
    .CK(clk),
    .D(salt_in[2]),
    .Q(salt_q[2]),
    .QN(_000_),
    .RN(rst_n)
  );
  DFFR_X1 _378_ (
    .CK(clk),
    .D(salt_in[3]),
    .Q(salt_q[3]),
    .QN(_189_),
    .RN(rst_n)
  );
  DFFR_X1 _379_ (
    .CK(clk),
    .D(salt_in[4]),
    .Q(salt_q[4]),
    .QN(_001_),
    .RN(rst_n)
  );
  DFFR_X1 _380_ (
    .CK(clk),
    .D(salt_in[5]),
    .Q(salt_q[5]),
    .QN(_190_),
    .RN(rst_n)
  );
  DFFR_X1 _381_ (
    .CK(clk),
    .D(salt_in[6]),
    .Q(salt_q[6]),
    .QN(_002_),
    .RN(rst_n)
  );
  DFFR_X1 _382_ (
    .CK(clk),
    .D(salt_in[7]),
    .Q(salt_q[7]),
    .QN(_191_),
    .RN(rst_n)
  );
  DFFR_X1 _383_ (
    .CK(clk),
    .D(salt_in[8]),
    .Q(salt_q[8]),
    .QN(_003_),
    .RN(rst_n)
  );
  DFFR_X1 _384_ (
    .CK(clk),
    .D(salt_in[9]),
    .Q(salt_q[9]),
    .QN(_192_),
    .RN(rst_n)
  );
  DFFR_X1 _385_ (
    .CK(clk),
    .D(salt_in[10]),
    .Q(salt_q[10]),
    .QN(_004_),
    .RN(rst_n)
  );
  DFFR_X1 _386_ (
    .CK(clk),
    .D(salt_in[11]),
    .Q(salt_q[11]),
    .QN(_193_),
    .RN(rst_n)
  );
  DFFR_X1 _387_ (
    .CK(clk),
    .D(salt_in[12]),
    .Q(salt_q[12]),
    .QN(_005_),
    .RN(rst_n)
  );
  DFFR_X1 _388_ (
    .CK(clk),
    .D(salt_in[13]),
    .Q(salt_q[13]),
    .QN(_194_),
    .RN(rst_n)
  );
  DFFR_X1 _389_ (
    .CK(clk),
    .D(salt_in[14]),
    .Q(salt_q[14]),
    .QN(_006_),
    .RN(rst_n)
  );
  DFFR_X1 _390_ (
    .CK(clk),
    .D(salt_in[15]),
    .Q(salt_q[15]),
    .QN(_195_),
    .RN(rst_n)
  );
  DFFR_X1 _391_ (
    .CK(clk),
    .D(salt_in[16]),
    .Q(salt_q[16]),
    .QN(_007_),
    .RN(rst_n)
  );
  DFFR_X1 _392_ (
    .CK(clk),
    .D(salt_in[17]),
    .Q(salt_q[17]),
    .QN(_196_),
    .RN(rst_n)
  );
  DFFR_X1 _393_ (
    .CK(clk),
    .D(salt_in[18]),
    .Q(salt_q[18]),
    .QN(_008_),
    .RN(rst_n)
  );
  DFFR_X1 _394_ (
    .CK(clk),
    .D(salt_in[19]),
    .Q(salt_q[19]),
    .QN(_197_),
    .RN(rst_n)
  );
  DFFR_X1 _395_ (
    .CK(clk),
    .D(salt_in[20]),
    .Q(salt_q[20]),
    .QN(_009_),
    .RN(rst_n)
  );
  DFFR_X1 _396_ (
    .CK(clk),
    .D(salt_in[21]),
    .Q(salt_q[21]),
    .QN(_198_),
    .RN(rst_n)
  );
  DFFR_X1 _397_ (
    .CK(clk),
    .D(salt_in[22]),
    .Q(salt_q[22]),
    .QN(_010_),
    .RN(rst_n)
  );
  DFFR_X1 _398_ (
    .CK(clk),
    .D(salt_in[23]),
    .Q(salt_q[23]),
    .QN(_199_),
    .RN(rst_n)
  );
  DFFR_X1 _399_ (
    .CK(clk),
    .D(salt_in[24]),
    .Q(salt_q[24]),
    .QN(_011_),
    .RN(rst_n)
  );
  DFFR_X1 _400_ (
    .CK(clk),
    .D(salt_in[25]),
    .Q(salt_q[25]),
    .QN(_200_),
    .RN(rst_n)
  );
  DFFR_X1 _401_ (
    .CK(clk),
    .D(salt_in[26]),
    .Q(salt_q[26]),
    .QN(_012_),
    .RN(rst_n)
  );
  DFFR_X1 _402_ (
    .CK(clk),
    .D(salt_in[27]),
    .Q(salt_q[27]),
    .QN(_201_),
    .RN(rst_n)
  );
  DFFR_X1 _403_ (
    .CK(clk),
    .D(salt_in[28]),
    .Q(salt_q[28]),
    .QN(_013_),
    .RN(rst_n)
  );
  DFFR_X1 _404_ (
    .CK(clk),
    .D(salt_in[29]),
    .Q(salt_q[29]),
    .QN(_202_),
    .RN(rst_n)
  );
  DFFR_X1 _405_ (
    .CK(clk),
    .D(salt_in[30]),
    .Q(salt_q[30]),
    .QN(_014_),
    .RN(rst_n)
  );
  DFFR_X1 _406_ (
    .CK(clk),
    .D(salt_in[31]),
    .Q(salt_q[31]),
    .QN(_122_),
    .RN(rst_n)
  );
endmodule
