/* Generated by Yosys 0.53 (git sha1 53c22ab7c0ced80861c7536c5dae682c30fb5834, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module tc(clk, rst_n, a_in, b_in, y_out, monitor_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  input [63:0] a_in;
  wire [63:0] a_in;
  wire [63:0] a_q;
  input [63:0] b_in;
  wire [63:0] b_in;
  wire [63:0] b_q;
  input clk;
  wire clk;
  wire cmp_eq;
  wire monitor_comb;
  output monitor_out;
  wire monitor_out;
  input rst_n;
  wire rst_n;
  output y_out;
  wire y_out;
  INV_X1 _223_ (
    .A(b_q[19]),
    .ZN(_000_)
  );
  INV_X1 _224_ (
    .A(a_q[27]),
    .ZN(_001_)
  );
  INV_X1 _225_ (
    .A(b_q[35]),
    .ZN(_002_)
  );
  INV_X1 _226_ (
    .A(a_q[35]),
    .ZN(_003_)
  );
  INV_X1 _227_ (
    .A(b_q[43]),
    .ZN(_004_)
  );
  XOR2_X1 _228_ (
    .A(b_q[13]),
    .B(a_q[13]),
    .Z(_005_)
  );
  XNOR2_X1 _229_ (
    .A(b_q[18]),
    .B(a_q[18]),
    .ZN(_006_)
  );
  XNOR2_X1 _230_ (
    .A(b_q[42]),
    .B(a_q[42]),
    .ZN(_007_)
  );
  XNOR2_X1 _231_ (
    .A(b_q[16]),
    .B(a_q[16]),
    .ZN(_008_)
  );
  XOR2_X1 _232_ (
    .A(b_q[15]),
    .B(a_q[15]),
    .Z(_009_)
  );
  XOR2_X1 _233_ (
    .A(b_q[14]),
    .B(a_q[14]),
    .Z(_010_)
  );
  XOR2_X1 _234_ (
    .A(b_q[7]),
    .B(a_q[7]),
    .Z(_011_)
  );
  XOR2_X1 _235_ (
    .A(b_q[1]),
    .B(a_q[1]),
    .Z(_012_)
  );
  XOR2_X1 _236_ (
    .A(b_q[47]),
    .B(a_q[47]),
    .Z(_013_)
  );
  XNOR2_X1 _237_ (
    .A(b_q[36]),
    .B(a_q[36]),
    .ZN(_014_)
  );
  XOR2_X1 _238_ (
    .A(b_q[31]),
    .B(a_q[31]),
    .Z(_015_)
  );
  XNOR2_X1 _239_ (
    .A(b_q[20]),
    .B(a_q[20]),
    .ZN(_016_)
  );
  XNOR2_X1 _240_ (
    .A(b_q[55]),
    .B(a_q[55]),
    .ZN(_017_)
  );
  XOR2_X1 _241_ (
    .A(b_q[9]),
    .B(a_q[9]),
    .Z(_018_)
  );
  XNOR2_X1 _242_ (
    .A(b_q[41]),
    .B(a_q[41]),
    .ZN(_019_)
  );
  XOR2_X1 _243_ (
    .A(b_q[44]),
    .B(a_q[44]),
    .Z(_020_)
  );
  XNOR2_X1 _244_ (
    .A(b_q[3]),
    .B(a_q[3]),
    .ZN(_021_)
  );
  XOR2_X1 _245_ (
    .A(b_q[34]),
    .B(a_q[34]),
    .Z(_022_)
  );
  XNOR2_X1 _246_ (
    .A(b_q[23]),
    .B(a_q[23]),
    .ZN(_023_)
  );
  XNOR2_X1 _247_ (
    .A(b_q[50]),
    .B(a_q[50]),
    .ZN(_024_)
  );
  XNOR2_X1 _248_ (
    .A(b_q[11]),
    .B(a_q[11]),
    .ZN(_025_)
  );
  XNOR2_X1 _249_ (
    .A(b_q[52]),
    .B(a_q[52]),
    .ZN(_026_)
  );
  XNOR2_X1 _250_ (
    .A(b_q[57]),
    .B(a_q[57]),
    .ZN(_027_)
  );
  XNOR2_X1 _251_ (
    .A(b_q[32]),
    .B(a_q[32]),
    .ZN(_028_)
  );
  XNOR2_X1 _252_ (
    .A(b_q[6]),
    .B(a_q[6]),
    .ZN(_029_)
  );
  XNOR2_X1 _253_ (
    .A(b_q[61]),
    .B(a_q[61]),
    .ZN(_030_)
  );
  XNOR2_X1 _254_ (
    .A(b_q[21]),
    .B(a_q[21]),
    .ZN(_031_)
  );
  XNOR2_X1 _255_ (
    .A(b_q[40]),
    .B(a_q[40]),
    .ZN(_032_)
  );
  XOR2_X1 _256_ (
    .A(b_q[29]),
    .B(a_q[29]),
    .Z(_033_)
  );
  XNOR2_X1 _257_ (
    .A(b_q[26]),
    .B(a_q[26]),
    .ZN(_034_)
  );
  XOR2_X1 _258_ (
    .A(b_q[48]),
    .B(a_q[48]),
    .Z(_035_)
  );
  XOR2_X1 _259_ (
    .A(b_q[58]),
    .B(a_q[58]),
    .Z(_036_)
  );
  XNOR2_X1 _260_ (
    .A(b_q[22]),
    .B(a_q[22]),
    .ZN(_037_)
  );
  XNOR2_X1 _261_ (
    .A(b_q[46]),
    .B(a_q[46]),
    .ZN(_038_)
  );
  XNOR2_X1 _262_ (
    .A(b_q[62]),
    .B(a_q[62]),
    .ZN(_039_)
  );
  XNOR2_X1 _263_ (
    .A(b_q[28]),
    .B(a_q[28]),
    .ZN(_040_)
  );
  XNOR2_X1 _264_ (
    .A(b_q[25]),
    .B(a_q[25]),
    .ZN(_041_)
  );
  XNOR2_X1 _265_ (
    .A(b_q[12]),
    .B(a_q[12]),
    .ZN(_042_)
  );
  XNOR2_X1 _266_ (
    .A(b_q[4]),
    .B(a_q[4]),
    .ZN(_043_)
  );
  XOR2_X1 _267_ (
    .A(b_q[60]),
    .B(a_q[60]),
    .Z(_044_)
  );
  XNOR2_X1 _268_ (
    .A(b_q[54]),
    .B(a_q[54]),
    .ZN(_045_)
  );
  XNOR2_X1 _269_ (
    .A(b_q[5]),
    .B(a_q[5]),
    .ZN(_046_)
  );
  XNOR2_X1 _270_ (
    .A(b_q[2]),
    .B(a_q[2]),
    .ZN(_047_)
  );
  XOR2_X1 _271_ (
    .A(b_q[17]),
    .B(a_q[17]),
    .Z(_048_)
  );
  XNOR2_X1 _272_ (
    .A(b_q[0]),
    .B(a_q[0]),
    .ZN(_049_)
  );
  XOR2_X1 _273_ (
    .A(b_q[39]),
    .B(a_q[39]),
    .Z(_050_)
  );
  XNOR2_X1 _274_ (
    .A(b_q[37]),
    .B(a_q[37]),
    .ZN(_051_)
  );
  XOR2_X1 _275_ (
    .A(b_q[24]),
    .B(a_q[24]),
    .Z(_052_)
  );
  XNOR2_X1 _276_ (
    .A(b_q[59]),
    .B(a_q[59]),
    .ZN(_053_)
  );
  XNOR2_X1 _277_ (
    .A(b_q[30]),
    .B(a_q[30]),
    .ZN(_054_)
  );
  XNOR2_X1 _278_ (
    .A(b_q[63]),
    .B(a_q[63]),
    .ZN(_055_)
  );
  XOR2_X1 _279_ (
    .A(b_q[53]),
    .B(a_q[53]),
    .Z(_056_)
  );
  XOR2_X1 _280_ (
    .A(b_q[8]),
    .B(a_q[8]),
    .Z(_057_)
  );
  XNOR2_X1 _281_ (
    .A(b_q[45]),
    .B(a_q[45]),
    .ZN(_058_)
  );
  NAND2_X1 _282_ (
    .A1(_042_),
    .A2(_049_),
    .ZN(_059_)
  );
  NOR3_X1 _283_ (
    .A1(_005_),
    .A2(_013_),
    .A3(_057_),
    .ZN(_060_)
  );
  XNOR2_X1 _284_ (
    .A(b_q[33]),
    .B(a_q[33]),
    .ZN(_061_)
  );
  OAI211_X1 _285_ (
    .A(_051_),
    .B(_061_),
    .C1(_004_),
    .C2(a_q[43]),
    .ZN(_062_)
  );
  XNOR2_X1 _286_ (
    .A(b_q[51]),
    .B(a_q[51]),
    .ZN(_063_)
  );
  NAND3_X1 _287_ (
    .A1(_027_),
    .A2(_028_),
    .A3(_063_),
    .ZN(_064_)
  );
  NAND4_X1 _288_ (
    .A1(_006_),
    .A2(_014_),
    .A3(_029_),
    .A4(_038_),
    .ZN(_065_)
  );
  XNOR2_X1 _289_ (
    .A(b_q[49]),
    .B(a_q[49]),
    .ZN(_066_)
  );
  NAND3_X1 _290_ (
    .A1(_053_),
    .A2(_058_),
    .A3(_066_),
    .ZN(_067_)
  );
  NOR4_X1 _291_ (
    .A1(_062_),
    .A2(_064_),
    .A3(_065_),
    .A4(_067_),
    .ZN(_068_)
  );
  NAND4_X1 _292_ (
    .A1(_026_),
    .A2(_032_),
    .A3(_060_),
    .A4(_068_),
    .ZN(_069_)
  );
  AOI21_X1 _293_ (
    .A(_044_),
    .B1(a_q[43]),
    .B2(_004_),
    .ZN(_070_)
  );
  NOR4_X1 _294_ (
    .A1(_011_),
    .A2(_018_),
    .A3(_033_),
    .A4(_052_),
    .ZN(_071_)
  );
  AND4_X1 _295_ (
    .A1(_017_),
    .A2(_045_),
    .A3(_070_),
    .A4(_071_),
    .ZN(_072_)
  );
  OAI211_X1 _296_ (
    .A(_039_),
    .B(_055_),
    .C1(b_q[35]),
    .C2(_003_),
    .ZN(_073_)
  );
  OAI21_X1 _297_ (
    .A(_019_),
    .B1(a_q[35]),
    .B2(_002_),
    .ZN(_074_)
  );
  NOR3_X1 _298_ (
    .A1(_020_),
    .A2(_073_),
    .A3(_074_),
    .ZN(_075_)
  );
  AOI211_X1 _299_ (
    .A(_012_),
    .B(_059_),
    .C1(_000_),
    .C2(a_q[19]),
    .ZN(_076_)
  );
  XOR2_X1 _300_ (
    .A(b_q[38]),
    .B(a_q[38]),
    .Z(_077_)
  );
  NOR2_X1 _301_ (
    .A1(_050_),
    .A2(_077_),
    .ZN(_078_)
  );
  NAND4_X1 _302_ (
    .A1(_072_),
    .A2(_075_),
    .A3(_076_),
    .A4(_078_),
    .ZN(_079_)
  );
  XNOR2_X1 _303_ (
    .A(b_q[10]),
    .B(a_q[10]),
    .ZN(_080_)
  );
  NAND4_X1 _304_ (
    .A1(_021_),
    .A2(_034_),
    .A3(_043_),
    .A4(_080_),
    .ZN(_081_)
  );
  OAI21_X1 _305_ (
    .A(_047_),
    .B1(_001_),
    .B2(b_q[27]),
    .ZN(_082_)
  );
  NOR4_X1 _306_ (
    .A1(_009_),
    .A2(_010_),
    .A3(_081_),
    .A4(_082_),
    .ZN(_083_)
  );
  NOR4_X1 _307_ (
    .A1(_022_),
    .A2(_035_),
    .A3(_036_),
    .A4(_056_),
    .ZN(_084_)
  );
  AOI211_X1 _308_ (
    .A(_015_),
    .B(_048_),
    .C1(b_q[27]),
    .C2(_001_),
    .ZN(_085_)
  );
  XNOR2_X1 _309_ (
    .A(b_q[56]),
    .B(a_q[56]),
    .ZN(_086_)
  );
  NAND4_X1 _310_ (
    .A1(_007_),
    .A2(_024_),
    .A3(_030_),
    .A4(_086_),
    .ZN(_087_)
  );
  NAND4_X1 _311_ (
    .A1(_008_),
    .A2(_025_),
    .A3(_031_),
    .A4(_046_),
    .ZN(_088_)
  );
  OAI211_X1 _312_ (
    .A(_040_),
    .B(_041_),
    .C1(_000_),
    .C2(a_q[19]),
    .ZN(_089_)
  );
  NAND4_X1 _313_ (
    .A1(_016_),
    .A2(_023_),
    .A3(_037_),
    .A4(_054_),
    .ZN(_090_)
  );
  NOR4_X1 _314_ (
    .A1(_087_),
    .A2(_088_),
    .A3(_089_),
    .A4(_090_),
    .ZN(_091_)
  );
  NAND4_X1 _315_ (
    .A1(_083_),
    .A2(_084_),
    .A3(_085_),
    .A4(_091_),
    .ZN(_092_)
  );
  NOR3_X1 _316_ (
    .A1(_069_),
    .A2(_079_),
    .A3(_092_),
    .ZN(cmp_eq)
  );
  BUF_X1 _317_ (
    .A(b_q[0]),
    .Z(monitor_comb)
  );
  DFFR_X1 _318_ (
    .CK(clk),
    .D(cmp_eq),
    .Q(y_out),
    .QN(_094_),
    .RN(rst_n)
  );
  DFFR_X1 _319_ (
    .CK(clk),
    .D(monitor_comb),
    .Q(monitor_out),
    .QN(_095_),
    .RN(rst_n)
  );
  DFFR_X1 _320_ (
    .CK(clk),
    .D(a_in[0]),
    .Q(a_q[0]),
    .QN(_096_),
    .RN(rst_n)
  );
  DFFR_X1 _321_ (
    .CK(clk),
    .D(a_in[1]),
    .Q(a_q[1]),
    .QN(_097_),
    .RN(rst_n)
  );
  DFFR_X1 _322_ (
    .CK(clk),
    .D(a_in[2]),
    .Q(a_q[2]),
    .QN(_098_),
    .RN(rst_n)
  );
  DFFR_X1 _323_ (
    .CK(clk),
    .D(a_in[3]),
    .Q(a_q[3]),
    .QN(_099_),
    .RN(rst_n)
  );
  DFFR_X1 _324_ (
    .CK(clk),
    .D(a_in[4]),
    .Q(a_q[4]),
    .QN(_100_),
    .RN(rst_n)
  );
  DFFR_X1 _325_ (
    .CK(clk),
    .D(a_in[5]),
    .Q(a_q[5]),
    .QN(_101_),
    .RN(rst_n)
  );
  DFFR_X1 _326_ (
    .CK(clk),
    .D(a_in[6]),
    .Q(a_q[6]),
    .QN(_102_),
    .RN(rst_n)
  );
  DFFR_X1 _327_ (
    .CK(clk),
    .D(a_in[7]),
    .Q(a_q[7]),
    .QN(_103_),
    .RN(rst_n)
  );
  DFFR_X1 _328_ (
    .CK(clk),
    .D(a_in[8]),
    .Q(a_q[8]),
    .QN(_104_),
    .RN(rst_n)
  );
  DFFR_X1 _329_ (
    .CK(clk),
    .D(a_in[9]),
    .Q(a_q[9]),
    .QN(_105_),
    .RN(rst_n)
  );
  DFFR_X1 _330_ (
    .CK(clk),
    .D(a_in[10]),
    .Q(a_q[10]),
    .QN(_106_),
    .RN(rst_n)
  );
  DFFR_X1 _331_ (
    .CK(clk),
    .D(a_in[11]),
    .Q(a_q[11]),
    .QN(_107_),
    .RN(rst_n)
  );
  DFFR_X1 _332_ (
    .CK(clk),
    .D(a_in[12]),
    .Q(a_q[12]),
    .QN(_108_),
    .RN(rst_n)
  );
  DFFR_X1 _333_ (
    .CK(clk),
    .D(a_in[13]),
    .Q(a_q[13]),
    .QN(_109_),
    .RN(rst_n)
  );
  DFFR_X1 _334_ (
    .CK(clk),
    .D(a_in[14]),
    .Q(a_q[14]),
    .QN(_110_),
    .RN(rst_n)
  );
  DFFR_X1 _335_ (
    .CK(clk),
    .D(a_in[15]),
    .Q(a_q[15]),
    .QN(_111_),
    .RN(rst_n)
  );
  DFFR_X1 _336_ (
    .CK(clk),
    .D(a_in[16]),
    .Q(a_q[16]),
    .QN(_112_),
    .RN(rst_n)
  );
  DFFR_X1 _337_ (
    .CK(clk),
    .D(a_in[17]),
    .Q(a_q[17]),
    .QN(_113_),
    .RN(rst_n)
  );
  DFFR_X1 _338_ (
    .CK(clk),
    .D(a_in[18]),
    .Q(a_q[18]),
    .QN(_114_),
    .RN(rst_n)
  );
  DFFR_X1 _339_ (
    .CK(clk),
    .D(a_in[19]),
    .Q(a_q[19]),
    .QN(_115_),
    .RN(rst_n)
  );
  DFFR_X1 _340_ (
    .CK(clk),
    .D(a_in[20]),
    .Q(a_q[20]),
    .QN(_116_),
    .RN(rst_n)
  );
  DFFR_X1 _341_ (
    .CK(clk),
    .D(a_in[21]),
    .Q(a_q[21]),
    .QN(_117_),
    .RN(rst_n)
  );
  DFFR_X1 _342_ (
    .CK(clk),
    .D(a_in[22]),
    .Q(a_q[22]),
    .QN(_118_),
    .RN(rst_n)
  );
  DFFR_X1 _343_ (
    .CK(clk),
    .D(a_in[23]),
    .Q(a_q[23]),
    .QN(_119_),
    .RN(rst_n)
  );
  DFFR_X1 _344_ (
    .CK(clk),
    .D(a_in[24]),
    .Q(a_q[24]),
    .QN(_120_),
    .RN(rst_n)
  );
  DFFR_X1 _345_ (
    .CK(clk),
    .D(a_in[25]),
    .Q(a_q[25]),
    .QN(_121_),
    .RN(rst_n)
  );
  DFFR_X1 _346_ (
    .CK(clk),
    .D(a_in[26]),
    .Q(a_q[26]),
    .QN(_122_),
    .RN(rst_n)
  );
  DFFR_X1 _347_ (
    .CK(clk),
    .D(a_in[27]),
    .Q(a_q[27]),
    .QN(_123_),
    .RN(rst_n)
  );
  DFFR_X1 _348_ (
    .CK(clk),
    .D(a_in[28]),
    .Q(a_q[28]),
    .QN(_124_),
    .RN(rst_n)
  );
  DFFR_X1 _349_ (
    .CK(clk),
    .D(a_in[29]),
    .Q(a_q[29]),
    .QN(_125_),
    .RN(rst_n)
  );
  DFFR_X1 _350_ (
    .CK(clk),
    .D(a_in[30]),
    .Q(a_q[30]),
    .QN(_126_),
    .RN(rst_n)
  );
  DFFR_X1 _351_ (
    .CK(clk),
    .D(a_in[31]),
    .Q(a_q[31]),
    .QN(_127_),
    .RN(rst_n)
  );
  DFFR_X1 _352_ (
    .CK(clk),
    .D(a_in[32]),
    .Q(a_q[32]),
    .QN(_128_),
    .RN(rst_n)
  );
  DFFR_X1 _353_ (
    .CK(clk),
    .D(a_in[33]),
    .Q(a_q[33]),
    .QN(_129_),
    .RN(rst_n)
  );
  DFFR_X1 _354_ (
    .CK(clk),
    .D(a_in[34]),
    .Q(a_q[34]),
    .QN(_130_),
    .RN(rst_n)
  );
  DFFR_X1 _355_ (
    .CK(clk),
    .D(a_in[35]),
    .Q(a_q[35]),
    .QN(_131_),
    .RN(rst_n)
  );
  DFFR_X1 _356_ (
    .CK(clk),
    .D(a_in[36]),
    .Q(a_q[36]),
    .QN(_132_),
    .RN(rst_n)
  );
  DFFR_X1 _357_ (
    .CK(clk),
    .D(a_in[37]),
    .Q(a_q[37]),
    .QN(_133_),
    .RN(rst_n)
  );
  DFFR_X1 _358_ (
    .CK(clk),
    .D(a_in[38]),
    .Q(a_q[38]),
    .QN(_134_),
    .RN(rst_n)
  );
  DFFR_X1 _359_ (
    .CK(clk),
    .D(a_in[39]),
    .Q(a_q[39]),
    .QN(_135_),
    .RN(rst_n)
  );
  DFFR_X1 _360_ (
    .CK(clk),
    .D(a_in[40]),
    .Q(a_q[40]),
    .QN(_136_),
    .RN(rst_n)
  );
  DFFR_X1 _361_ (
    .CK(clk),
    .D(a_in[41]),
    .Q(a_q[41]),
    .QN(_137_),
    .RN(rst_n)
  );
  DFFR_X1 _362_ (
    .CK(clk),
    .D(a_in[42]),
    .Q(a_q[42]),
    .QN(_138_),
    .RN(rst_n)
  );
  DFFR_X1 _363_ (
    .CK(clk),
    .D(a_in[43]),
    .Q(a_q[43]),
    .QN(_139_),
    .RN(rst_n)
  );
  DFFR_X1 _364_ (
    .CK(clk),
    .D(a_in[44]),
    .Q(a_q[44]),
    .QN(_140_),
    .RN(rst_n)
  );
  DFFR_X1 _365_ (
    .CK(clk),
    .D(a_in[45]),
    .Q(a_q[45]),
    .QN(_141_),
    .RN(rst_n)
  );
  DFFR_X1 _366_ (
    .CK(clk),
    .D(a_in[46]),
    .Q(a_q[46]),
    .QN(_142_),
    .RN(rst_n)
  );
  DFFR_X1 _367_ (
    .CK(clk),
    .D(a_in[47]),
    .Q(a_q[47]),
    .QN(_143_),
    .RN(rst_n)
  );
  DFFR_X1 _368_ (
    .CK(clk),
    .D(a_in[48]),
    .Q(a_q[48]),
    .QN(_144_),
    .RN(rst_n)
  );
  DFFR_X1 _369_ (
    .CK(clk),
    .D(a_in[49]),
    .Q(a_q[49]),
    .QN(_145_),
    .RN(rst_n)
  );
  DFFR_X1 _370_ (
    .CK(clk),
    .D(a_in[50]),
    .Q(a_q[50]),
    .QN(_146_),
    .RN(rst_n)
  );
  DFFR_X1 _371_ (
    .CK(clk),
    .D(a_in[51]),
    .Q(a_q[51]),
    .QN(_147_),
    .RN(rst_n)
  );
  DFFR_X1 _372_ (
    .CK(clk),
    .D(a_in[52]),
    .Q(a_q[52]),
    .QN(_148_),
    .RN(rst_n)
  );
  DFFR_X1 _373_ (
    .CK(clk),
    .D(a_in[53]),
    .Q(a_q[53]),
    .QN(_149_),
    .RN(rst_n)
  );
  DFFR_X1 _374_ (
    .CK(clk),
    .D(a_in[54]),
    .Q(a_q[54]),
    .QN(_150_),
    .RN(rst_n)
  );
  DFFR_X1 _375_ (
    .CK(clk),
    .D(a_in[55]),
    .Q(a_q[55]),
    .QN(_151_),
    .RN(rst_n)
  );
  DFFR_X1 _376_ (
    .CK(clk),
    .D(a_in[56]),
    .Q(a_q[56]),
    .QN(_152_),
    .RN(rst_n)
  );
  DFFR_X1 _377_ (
    .CK(clk),
    .D(a_in[57]),
    .Q(a_q[57]),
    .QN(_153_),
    .RN(rst_n)
  );
  DFFR_X1 _378_ (
    .CK(clk),
    .D(a_in[58]),
    .Q(a_q[58]),
    .QN(_154_),
    .RN(rst_n)
  );
  DFFR_X1 _379_ (
    .CK(clk),
    .D(a_in[59]),
    .Q(a_q[59]),
    .QN(_155_),
    .RN(rst_n)
  );
  DFFR_X1 _380_ (
    .CK(clk),
    .D(a_in[60]),
    .Q(a_q[60]),
    .QN(_156_),
    .RN(rst_n)
  );
  DFFR_X1 _381_ (
    .CK(clk),
    .D(a_in[61]),
    .Q(a_q[61]),
    .QN(_157_),
    .RN(rst_n)
  );
  DFFR_X1 _382_ (
    .CK(clk),
    .D(a_in[62]),
    .Q(a_q[62]),
    .QN(_158_),
    .RN(rst_n)
  );
  DFFR_X1 _383_ (
    .CK(clk),
    .D(a_in[63]),
    .Q(a_q[63]),
    .QN(_159_),
    .RN(rst_n)
  );
  DFFR_X1 _384_ (
    .CK(clk),
    .D(b_in[0]),
    .Q(b_q[0]),
    .QN(_160_),
    .RN(rst_n)
  );
  DFFR_X1 _385_ (
    .CK(clk),
    .D(b_in[1]),
    .Q(b_q[1]),
    .QN(_161_),
    .RN(rst_n)
  );
  DFFR_X1 _386_ (
    .CK(clk),
    .D(b_in[2]),
    .Q(b_q[2]),
    .QN(_162_),
    .RN(rst_n)
  );
  DFFR_X1 _387_ (
    .CK(clk),
    .D(b_in[3]),
    .Q(b_q[3]),
    .QN(_163_),
    .RN(rst_n)
  );
  DFFR_X1 _388_ (
    .CK(clk),
    .D(b_in[4]),
    .Q(b_q[4]),
    .QN(_164_),
    .RN(rst_n)
  );
  DFFR_X1 _389_ (
    .CK(clk),
    .D(b_in[5]),
    .Q(b_q[5]),
    .QN(_165_),
    .RN(rst_n)
  );
  DFFR_X1 _390_ (
    .CK(clk),
    .D(b_in[6]),
    .Q(b_q[6]),
    .QN(_166_),
    .RN(rst_n)
  );
  DFFR_X1 _391_ (
    .CK(clk),
    .D(b_in[7]),
    .Q(b_q[7]),
    .QN(_167_),
    .RN(rst_n)
  );
  DFFR_X1 _392_ (
    .CK(clk),
    .D(b_in[8]),
    .Q(b_q[8]),
    .QN(_168_),
    .RN(rst_n)
  );
  DFFR_X1 _393_ (
    .CK(clk),
    .D(b_in[9]),
    .Q(b_q[9]),
    .QN(_169_),
    .RN(rst_n)
  );
  DFFR_X1 _394_ (
    .CK(clk),
    .D(b_in[10]),
    .Q(b_q[10]),
    .QN(_170_),
    .RN(rst_n)
  );
  DFFR_X1 _395_ (
    .CK(clk),
    .D(b_in[11]),
    .Q(b_q[11]),
    .QN(_171_),
    .RN(rst_n)
  );
  DFFR_X1 _396_ (
    .CK(clk),
    .D(b_in[12]),
    .Q(b_q[12]),
    .QN(_172_),
    .RN(rst_n)
  );
  DFFR_X1 _397_ (
    .CK(clk),
    .D(b_in[13]),
    .Q(b_q[13]),
    .QN(_173_),
    .RN(rst_n)
  );
  DFFR_X1 _398_ (
    .CK(clk),
    .D(b_in[14]),
    .Q(b_q[14]),
    .QN(_174_),
    .RN(rst_n)
  );
  DFFR_X1 _399_ (
    .CK(clk),
    .D(b_in[15]),
    .Q(b_q[15]),
    .QN(_175_),
    .RN(rst_n)
  );
  DFFR_X1 _400_ (
    .CK(clk),
    .D(b_in[16]),
    .Q(b_q[16]),
    .QN(_176_),
    .RN(rst_n)
  );
  DFFR_X1 _401_ (
    .CK(clk),
    .D(b_in[17]),
    .Q(b_q[17]),
    .QN(_177_),
    .RN(rst_n)
  );
  DFFR_X1 _402_ (
    .CK(clk),
    .D(b_in[18]),
    .Q(b_q[18]),
    .QN(_178_),
    .RN(rst_n)
  );
  DFFR_X1 _403_ (
    .CK(clk),
    .D(b_in[19]),
    .Q(b_q[19]),
    .QN(_179_),
    .RN(rst_n)
  );
  DFFR_X1 _404_ (
    .CK(clk),
    .D(b_in[20]),
    .Q(b_q[20]),
    .QN(_180_),
    .RN(rst_n)
  );
  DFFR_X1 _405_ (
    .CK(clk),
    .D(b_in[21]),
    .Q(b_q[21]),
    .QN(_181_),
    .RN(rst_n)
  );
  DFFR_X1 _406_ (
    .CK(clk),
    .D(b_in[22]),
    .Q(b_q[22]),
    .QN(_182_),
    .RN(rst_n)
  );
  DFFR_X1 _407_ (
    .CK(clk),
    .D(b_in[23]),
    .Q(b_q[23]),
    .QN(_183_),
    .RN(rst_n)
  );
  DFFR_X1 _408_ (
    .CK(clk),
    .D(b_in[24]),
    .Q(b_q[24]),
    .QN(_184_),
    .RN(rst_n)
  );
  DFFR_X1 _409_ (
    .CK(clk),
    .D(b_in[25]),
    .Q(b_q[25]),
    .QN(_185_),
    .RN(rst_n)
  );
  DFFR_X1 _410_ (
    .CK(clk),
    .D(b_in[26]),
    .Q(b_q[26]),
    .QN(_186_),
    .RN(rst_n)
  );
  DFFR_X1 _411_ (
    .CK(clk),
    .D(b_in[27]),
    .Q(b_q[27]),
    .QN(_187_),
    .RN(rst_n)
  );
  DFFR_X1 _412_ (
    .CK(clk),
    .D(b_in[28]),
    .Q(b_q[28]),
    .QN(_188_),
    .RN(rst_n)
  );
  DFFR_X1 _413_ (
    .CK(clk),
    .D(b_in[29]),
    .Q(b_q[29]),
    .QN(_189_),
    .RN(rst_n)
  );
  DFFR_X1 _414_ (
    .CK(clk),
    .D(b_in[30]),
    .Q(b_q[30]),
    .QN(_190_),
    .RN(rst_n)
  );
  DFFR_X1 _415_ (
    .CK(clk),
    .D(b_in[31]),
    .Q(b_q[31]),
    .QN(_191_),
    .RN(rst_n)
  );
  DFFR_X1 _416_ (
    .CK(clk),
    .D(b_in[32]),
    .Q(b_q[32]),
    .QN(_192_),
    .RN(rst_n)
  );
  DFFR_X1 _417_ (
    .CK(clk),
    .D(b_in[33]),
    .Q(b_q[33]),
    .QN(_193_),
    .RN(rst_n)
  );
  DFFR_X1 _418_ (
    .CK(clk),
    .D(b_in[34]),
    .Q(b_q[34]),
    .QN(_194_),
    .RN(rst_n)
  );
  DFFR_X1 _419_ (
    .CK(clk),
    .D(b_in[35]),
    .Q(b_q[35]),
    .QN(_195_),
    .RN(rst_n)
  );
  DFFR_X1 _420_ (
    .CK(clk),
    .D(b_in[36]),
    .Q(b_q[36]),
    .QN(_196_),
    .RN(rst_n)
  );
  DFFR_X1 _421_ (
    .CK(clk),
    .D(b_in[37]),
    .Q(b_q[37]),
    .QN(_197_),
    .RN(rst_n)
  );
  DFFR_X1 _422_ (
    .CK(clk),
    .D(b_in[38]),
    .Q(b_q[38]),
    .QN(_198_),
    .RN(rst_n)
  );
  DFFR_X1 _423_ (
    .CK(clk),
    .D(b_in[39]),
    .Q(b_q[39]),
    .QN(_199_),
    .RN(rst_n)
  );
  DFFR_X1 _424_ (
    .CK(clk),
    .D(b_in[40]),
    .Q(b_q[40]),
    .QN(_200_),
    .RN(rst_n)
  );
  DFFR_X1 _425_ (
    .CK(clk),
    .D(b_in[41]),
    .Q(b_q[41]),
    .QN(_201_),
    .RN(rst_n)
  );
  DFFR_X1 _426_ (
    .CK(clk),
    .D(b_in[42]),
    .Q(b_q[42]),
    .QN(_202_),
    .RN(rst_n)
  );
  DFFR_X1 _427_ (
    .CK(clk),
    .D(b_in[43]),
    .Q(b_q[43]),
    .QN(_203_),
    .RN(rst_n)
  );
  DFFR_X1 _428_ (
    .CK(clk),
    .D(b_in[44]),
    .Q(b_q[44]),
    .QN(_204_),
    .RN(rst_n)
  );
  DFFR_X1 _429_ (
    .CK(clk),
    .D(b_in[45]),
    .Q(b_q[45]),
    .QN(_205_),
    .RN(rst_n)
  );
  DFFR_X1 _430_ (
    .CK(clk),
    .D(b_in[46]),
    .Q(b_q[46]),
    .QN(_206_),
    .RN(rst_n)
  );
  DFFR_X1 _431_ (
    .CK(clk),
    .D(b_in[47]),
    .Q(b_q[47]),
    .QN(_207_),
    .RN(rst_n)
  );
  DFFR_X1 _432_ (
    .CK(clk),
    .D(b_in[48]),
    .Q(b_q[48]),
    .QN(_208_),
    .RN(rst_n)
  );
  DFFR_X1 _433_ (
    .CK(clk),
    .D(b_in[49]),
    .Q(b_q[49]),
    .QN(_209_),
    .RN(rst_n)
  );
  DFFR_X1 _434_ (
    .CK(clk),
    .D(b_in[50]),
    .Q(b_q[50]),
    .QN(_210_),
    .RN(rst_n)
  );
  DFFR_X1 _435_ (
    .CK(clk),
    .D(b_in[51]),
    .Q(b_q[51]),
    .QN(_211_),
    .RN(rst_n)
  );
  DFFR_X1 _436_ (
    .CK(clk),
    .D(b_in[52]),
    .Q(b_q[52]),
    .QN(_212_),
    .RN(rst_n)
  );
  DFFR_X1 _437_ (
    .CK(clk),
    .D(b_in[53]),
    .Q(b_q[53]),
    .QN(_213_),
    .RN(rst_n)
  );
  DFFR_X1 _438_ (
    .CK(clk),
    .D(b_in[54]),
    .Q(b_q[54]),
    .QN(_214_),
    .RN(rst_n)
  );
  DFFR_X1 _439_ (
    .CK(clk),
    .D(b_in[55]),
    .Q(b_q[55]),
    .QN(_215_),
    .RN(rst_n)
  );
  DFFR_X1 _440_ (
    .CK(clk),
    .D(b_in[56]),
    .Q(b_q[56]),
    .QN(_216_),
    .RN(rst_n)
  );
  DFFR_X1 _441_ (
    .CK(clk),
    .D(b_in[57]),
    .Q(b_q[57]),
    .QN(_217_),
    .RN(rst_n)
  );
  DFFR_X1 _442_ (
    .CK(clk),
    .D(b_in[58]),
    .Q(b_q[58]),
    .QN(_218_),
    .RN(rst_n)
  );
  DFFR_X1 _443_ (
    .CK(clk),
    .D(b_in[59]),
    .Q(b_q[59]),
    .QN(_219_),
    .RN(rst_n)
  );
  DFFR_X1 _444_ (
    .CK(clk),
    .D(b_in[60]),
    .Q(b_q[60]),
    .QN(_220_),
    .RN(rst_n)
  );
  DFFR_X1 _445_ (
    .CK(clk),
    .D(b_in[61]),
    .Q(b_q[61]),
    .QN(_221_),
    .RN(rst_n)
  );
  DFFR_X1 _446_ (
    .CK(clk),
    .D(b_in[62]),
    .Q(b_q[62]),
    .QN(_222_),
    .RN(rst_n)
  );
  DFFR_X1 _447_ (
    .CK(clk),
    .D(b_in[63]),
    .Q(b_q[63]),
    .QN(_093_),
    .RN(rst_n)
  );
endmodule
