/* Generated by Yosys 0.53 (git sha1 53c22ab7c0ced80861c7536c5dae682c30fb5834, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module tc(clk, rst_n, a_in, b_in, y_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  input [31:0] a_in;
  wire [31:0] a_in;
  wire [31:0] a_q;
  input [31:0] b_in;
  wire [31:0] b_in;
  wire [31:0] b_q;
  input clk;
  wire clk;
  wire cmp_eq;
  input rst_n;
  wire rst_n;
  output y_out;
  wire y_out;
  INV_X1 _112_ (
    .A(b_q[19]),
    .ZN(_013_)
  );
  INV_X1 _113_ (
    .A(a_q[19]),
    .ZN(_014_)
  );
  INV_X1 _114_ (
    .A(b_q[27]),
    .ZN(_015_)
  );
  INV_X1 _115_ (
    .A(a_q[27]),
    .ZN(_016_)
  );
  XOR2_X1 _116_ (
    .A(b_q[1]),
    .B(a_q[1]),
    .Z(_017_)
  );
  XOR2_X1 _117_ (
    .A(b_q[15]),
    .B(a_q[15]),
    .Z(_018_)
  );
  XOR2_X1 _118_ (
    .A(b_q[4]),
    .B(a_q[4]),
    .Z(_019_)
  );
  XOR2_X1 _119_ (
    .A(b_q[5]),
    .B(a_q[5]),
    .Z(_020_)
  );
  XOR2_X1 _120_ (
    .A(b_q[25]),
    .B(a_q[25]),
    .Z(_021_)
  );
  XOR2_X1 _121_ (
    .A(b_q[22]),
    .B(a_q[22]),
    .Z(_022_)
  );
  XOR2_X1 _122_ (
    .A(b_q[3]),
    .B(a_q[3]),
    .Z(_023_)
  );
  XOR2_X1 _123_ (
    .A(b_q[10]),
    .B(a_q[10]),
    .Z(_024_)
  );
  XNOR2_X1 _124_ (
    .A(b_q[20]),
    .B(a_q[20]),
    .ZN(_025_)
  );
  XOR2_X1 _125_ (
    .A(b_q[23]),
    .B(a_q[23]),
    .Z(_026_)
  );
  XOR2_X1 _126_ (
    .A(b_q[28]),
    .B(a_q[28]),
    .Z(_027_)
  );
  XOR2_X1 _127_ (
    .A(b_q[24]),
    .B(a_q[24]),
    .Z(_028_)
  );
  XOR2_X1 _128_ (
    .A(b_q[14]),
    .B(a_q[14]),
    .Z(_029_)
  );
  XOR2_X1 _129_ (
    .A(b_q[8]),
    .B(a_q[8]),
    .Z(_030_)
  );
  XNOR2_X1 _130_ (
    .A(b_q[30]),
    .B(a_q[30]),
    .ZN(_031_)
  );
  XOR2_X1 _131_ (
    .A(b_q[17]),
    .B(a_q[17]),
    .Z(_032_)
  );
  XOR2_X1 _132_ (
    .A(b_q[9]),
    .B(a_q[9]),
    .Z(_033_)
  );
  XOR2_X1 _133_ (
    .A(b_q[7]),
    .B(a_q[7]),
    .Z(_034_)
  );
  XOR2_X1 _134_ (
    .A(b_q[18]),
    .B(a_q[18]),
    .Z(_035_)
  );
  XOR2_X1 _135_ (
    .A(b_q[29]),
    .B(a_q[29]),
    .Z(_036_)
  );
  XOR2_X1 _136_ (
    .A(b_q[16]),
    .B(a_q[16]),
    .Z(_037_)
  );
  XOR2_X1 _137_ (
    .A(b_q[21]),
    .B(a_q[21]),
    .Z(_038_)
  );
  XOR2_X1 _138_ (
    .A(b_q[13]),
    .B(a_q[13]),
    .Z(_039_)
  );
  XOR2_X1 _139_ (
    .A(b_q[12]),
    .B(a_q[12]),
    .Z(_040_)
  );
  XOR2_X1 _140_ (
    .A(b_q[26]),
    .B(a_q[26]),
    .Z(_041_)
  );
  XOR2_X1 _141_ (
    .A(b_q[11]),
    .B(a_q[11]),
    .Z(_042_)
  );
  XOR2_X1 _142_ (
    .A(b_q[31]),
    .B(a_q[31]),
    .Z(_043_)
  );
  XOR2_X1 _143_ (
    .A(b_q[0]),
    .B(a_q[0]),
    .Z(_044_)
  );
  NOR4_X1 _144_ (
    .A1(_019_),
    .A2(_023_),
    .A3(_024_),
    .A4(_041_),
    .ZN(_045_)
  );
  NOR4_X1 _145_ (
    .A1(_020_),
    .A2(_037_),
    .A3(_038_),
    .A4(_042_),
    .ZN(_046_)
  );
  NAND4_X1 _146_ (
    .A1(_025_),
    .A2(_031_),
    .A3(_045_),
    .A4(_046_),
    .ZN(_000_)
  );
  XOR2_X1 _147_ (
    .A(b_q[2]),
    .B(a_q[2]),
    .Z(_001_)
  );
  AOI21_X1 _148_ (
    .A(_001_),
    .B1(a_q[27]),
    .B2(_015_),
    .ZN(_002_)
  );
  NOR2_X1 _149_ (
    .A1(_018_),
    .A2(_029_),
    .ZN(_003_)
  );
  XOR2_X1 _150_ (
    .A(b_q[6]),
    .B(a_q[6]),
    .Z(_004_)
  );
  NOR4_X1 _151_ (
    .A1(_030_),
    .A2(_035_),
    .A3(_039_),
    .A4(_004_),
    .ZN(_005_)
  );
  AOI211_X1 _152_ (
    .A(_032_),
    .B(_043_),
    .C1(b_q[27]),
    .C2(_016_),
    .ZN(_006_)
  );
  NAND4_X1 _153_ (
    .A1(_002_),
    .A2(_003_),
    .A3(_005_),
    .A4(_006_),
    .ZN(_007_)
  );
  AOI211_X1 _154_ (
    .A(_017_),
    .B(_044_),
    .C1(_013_),
    .C2(a_q[19]),
    .ZN(_008_)
  );
  AOI211_X1 _155_ (
    .A(_021_),
    .B(_027_),
    .C1(b_q[19]),
    .C2(_014_),
    .ZN(_009_)
  );
  NOR3_X1 _156_ (
    .A1(_033_),
    .A2(_034_),
    .A3(_036_),
    .ZN(_010_)
  );
  NOR4_X1 _157_ (
    .A1(_022_),
    .A2(_026_),
    .A3(_028_),
    .A4(_040_),
    .ZN(_011_)
  );
  NAND4_X1 _158_ (
    .A1(_008_),
    .A2(_009_),
    .A3(_010_),
    .A4(_011_),
    .ZN(_012_)
  );
  NOR3_X1 _159_ (
    .A1(_000_),
    .A2(_007_),
    .A3(_012_),
    .ZN(cmp_eq)
  );
  DFFR_X1 _160_ (
    .CK(clk),
    .D(cmp_eq),
    .Q(y_out),
    .QN(_048_),
    .RN(rst_n)
  );
  DFFR_X1 _161_ (
    .CK(clk),
    .D(a_in[0]),
    .Q(a_q[0]),
    .QN(_049_),
    .RN(rst_n)
  );
  DFFR_X1 _162_ (
    .CK(clk),
    .D(a_in[1]),
    .Q(a_q[1]),
    .QN(_050_),
    .RN(rst_n)
  );
  DFFR_X1 _163_ (
    .CK(clk),
    .D(a_in[2]),
    .Q(a_q[2]),
    .QN(_051_),
    .RN(rst_n)
  );
  DFFR_X1 _164_ (
    .CK(clk),
    .D(a_in[3]),
    .Q(a_q[3]),
    .QN(_052_),
    .RN(rst_n)
  );
  DFFR_X1 _165_ (
    .CK(clk),
    .D(a_in[4]),
    .Q(a_q[4]),
    .QN(_053_),
    .RN(rst_n)
  );
  DFFR_X1 _166_ (
    .CK(clk),
    .D(a_in[5]),
    .Q(a_q[5]),
    .QN(_054_),
    .RN(rst_n)
  );
  DFFR_X1 _167_ (
    .CK(clk),
    .D(a_in[6]),
    .Q(a_q[6]),
    .QN(_055_),
    .RN(rst_n)
  );
  DFFR_X1 _168_ (
    .CK(clk),
    .D(a_in[7]),
    .Q(a_q[7]),
    .QN(_056_),
    .RN(rst_n)
  );
  DFFR_X1 _169_ (
    .CK(clk),
    .D(a_in[8]),
    .Q(a_q[8]),
    .QN(_057_),
    .RN(rst_n)
  );
  DFFR_X1 _170_ (
    .CK(clk),
    .D(a_in[9]),
    .Q(a_q[9]),
    .QN(_058_),
    .RN(rst_n)
  );
  DFFR_X1 _171_ (
    .CK(clk),
    .D(a_in[10]),
    .Q(a_q[10]),
    .QN(_059_),
    .RN(rst_n)
  );
  DFFR_X1 _172_ (
    .CK(clk),
    .D(a_in[11]),
    .Q(a_q[11]),
    .QN(_060_),
    .RN(rst_n)
  );
  DFFR_X1 _173_ (
    .CK(clk),
    .D(a_in[12]),
    .Q(a_q[12]),
    .QN(_061_),
    .RN(rst_n)
  );
  DFFR_X1 _174_ (
    .CK(clk),
    .D(a_in[13]),
    .Q(a_q[13]),
    .QN(_062_),
    .RN(rst_n)
  );
  DFFR_X1 _175_ (
    .CK(clk),
    .D(a_in[14]),
    .Q(a_q[14]),
    .QN(_063_),
    .RN(rst_n)
  );
  DFFR_X1 _176_ (
    .CK(clk),
    .D(a_in[15]),
    .Q(a_q[15]),
    .QN(_064_),
    .RN(rst_n)
  );
  DFFR_X1 _177_ (
    .CK(clk),
    .D(a_in[16]),
    .Q(a_q[16]),
    .QN(_065_),
    .RN(rst_n)
  );
  DFFR_X1 _178_ (
    .CK(clk),
    .D(a_in[17]),
    .Q(a_q[17]),
    .QN(_066_),
    .RN(rst_n)
  );
  DFFR_X1 _179_ (
    .CK(clk),
    .D(a_in[18]),
    .Q(a_q[18]),
    .QN(_067_),
    .RN(rst_n)
  );
  DFFR_X1 _180_ (
    .CK(clk),
    .D(a_in[19]),
    .Q(a_q[19]),
    .QN(_068_),
    .RN(rst_n)
  );
  DFFR_X1 _181_ (
    .CK(clk),
    .D(a_in[20]),
    .Q(a_q[20]),
    .QN(_069_),
    .RN(rst_n)
  );
  DFFR_X1 _182_ (
    .CK(clk),
    .D(a_in[21]),
    .Q(a_q[21]),
    .QN(_070_),
    .RN(rst_n)
  );
  DFFR_X1 _183_ (
    .CK(clk),
    .D(a_in[22]),
    .Q(a_q[22]),
    .QN(_071_),
    .RN(rst_n)
  );
  DFFR_X1 _184_ (
    .CK(clk),
    .D(a_in[23]),
    .Q(a_q[23]),
    .QN(_072_),
    .RN(rst_n)
  );
  DFFR_X1 _185_ (
    .CK(clk),
    .D(a_in[24]),
    .Q(a_q[24]),
    .QN(_073_),
    .RN(rst_n)
  );
  DFFR_X1 _186_ (
    .CK(clk),
    .D(a_in[25]),
    .Q(a_q[25]),
    .QN(_074_),
    .RN(rst_n)
  );
  DFFR_X1 _187_ (
    .CK(clk),
    .D(a_in[26]),
    .Q(a_q[26]),
    .QN(_075_),
    .RN(rst_n)
  );
  DFFR_X1 _188_ (
    .CK(clk),
    .D(a_in[27]),
    .Q(a_q[27]),
    .QN(_076_),
    .RN(rst_n)
  );
  DFFR_X1 _189_ (
    .CK(clk),
    .D(a_in[28]),
    .Q(a_q[28]),
    .QN(_077_),
    .RN(rst_n)
  );
  DFFR_X1 _190_ (
    .CK(clk),
    .D(a_in[29]),
    .Q(a_q[29]),
    .QN(_078_),
    .RN(rst_n)
  );
  DFFR_X1 _191_ (
    .CK(clk),
    .D(a_in[30]),
    .Q(a_q[30]),
    .QN(_079_),
    .RN(rst_n)
  );
  DFFR_X1 _192_ (
    .CK(clk),
    .D(a_in[31]),
    .Q(a_q[31]),
    .QN(_080_),
    .RN(rst_n)
  );
  DFFR_X1 _193_ (
    .CK(clk),
    .D(b_in[0]),
    .Q(b_q[0]),
    .QN(_081_),
    .RN(rst_n)
  );
  DFFR_X1 _194_ (
    .CK(clk),
    .D(b_in[1]),
    .Q(b_q[1]),
    .QN(_082_),
    .RN(rst_n)
  );
  DFFR_X1 _195_ (
    .CK(clk),
    .D(b_in[2]),
    .Q(b_q[2]),
    .QN(_083_),
    .RN(rst_n)
  );
  DFFR_X1 _196_ (
    .CK(clk),
    .D(b_in[3]),
    .Q(b_q[3]),
    .QN(_084_),
    .RN(rst_n)
  );
  DFFR_X1 _197_ (
    .CK(clk),
    .D(b_in[4]),
    .Q(b_q[4]),
    .QN(_085_),
    .RN(rst_n)
  );
  DFFR_X1 _198_ (
    .CK(clk),
    .D(b_in[5]),
    .Q(b_q[5]),
    .QN(_086_),
    .RN(rst_n)
  );
  DFFR_X1 _199_ (
    .CK(clk),
    .D(b_in[6]),
    .Q(b_q[6]),
    .QN(_087_),
    .RN(rst_n)
  );
  DFFR_X1 _200_ (
    .CK(clk),
    .D(b_in[7]),
    .Q(b_q[7]),
    .QN(_088_),
    .RN(rst_n)
  );
  DFFR_X1 _201_ (
    .CK(clk),
    .D(b_in[8]),
    .Q(b_q[8]),
    .QN(_089_),
    .RN(rst_n)
  );
  DFFR_X1 _202_ (
    .CK(clk),
    .D(b_in[9]),
    .Q(b_q[9]),
    .QN(_090_),
    .RN(rst_n)
  );
  DFFR_X1 _203_ (
    .CK(clk),
    .D(b_in[10]),
    .Q(b_q[10]),
    .QN(_091_),
    .RN(rst_n)
  );
  DFFR_X1 _204_ (
    .CK(clk),
    .D(b_in[11]),
    .Q(b_q[11]),
    .QN(_092_),
    .RN(rst_n)
  );
  DFFR_X1 _205_ (
    .CK(clk),
    .D(b_in[12]),
    .Q(b_q[12]),
    .QN(_093_),
    .RN(rst_n)
  );
  DFFR_X1 _206_ (
    .CK(clk),
    .D(b_in[13]),
    .Q(b_q[13]),
    .QN(_094_),
    .RN(rst_n)
  );
  DFFR_X1 _207_ (
    .CK(clk),
    .D(b_in[14]),
    .Q(b_q[14]),
    .QN(_095_),
    .RN(rst_n)
  );
  DFFR_X1 _208_ (
    .CK(clk),
    .D(b_in[15]),
    .Q(b_q[15]),
    .QN(_096_),
    .RN(rst_n)
  );
  DFFR_X1 _209_ (
    .CK(clk),
    .D(b_in[16]),
    .Q(b_q[16]),
    .QN(_097_),
    .RN(rst_n)
  );
  DFFR_X1 _210_ (
    .CK(clk),
    .D(b_in[17]),
    .Q(b_q[17]),
    .QN(_098_),
    .RN(rst_n)
  );
  DFFR_X1 _211_ (
    .CK(clk),
    .D(b_in[18]),
    .Q(b_q[18]),
    .QN(_099_),
    .RN(rst_n)
  );
  DFFR_X1 _212_ (
    .CK(clk),
    .D(b_in[19]),
    .Q(b_q[19]),
    .QN(_100_),
    .RN(rst_n)
  );
  DFFR_X1 _213_ (
    .CK(clk),
    .D(b_in[20]),
    .Q(b_q[20]),
    .QN(_101_),
    .RN(rst_n)
  );
  DFFR_X1 _214_ (
    .CK(clk),
    .D(b_in[21]),
    .Q(b_q[21]),
    .QN(_102_),
    .RN(rst_n)
  );
  DFFR_X1 _215_ (
    .CK(clk),
    .D(b_in[22]),
    .Q(b_q[22]),
    .QN(_103_),
    .RN(rst_n)
  );
  DFFR_X1 _216_ (
    .CK(clk),
    .D(b_in[23]),
    .Q(b_q[23]),
    .QN(_104_),
    .RN(rst_n)
  );
  DFFR_X1 _217_ (
    .CK(clk),
    .D(b_in[24]),
    .Q(b_q[24]),
    .QN(_105_),
    .RN(rst_n)
  );
  DFFR_X1 _218_ (
    .CK(clk),
    .D(b_in[25]),
    .Q(b_q[25]),
    .QN(_106_),
    .RN(rst_n)
  );
  DFFR_X1 _219_ (
    .CK(clk),
    .D(b_in[26]),
    .Q(b_q[26]),
    .QN(_107_),
    .RN(rst_n)
  );
  DFFR_X1 _220_ (
    .CK(clk),
    .D(b_in[27]),
    .Q(b_q[27]),
    .QN(_108_),
    .RN(rst_n)
  );
  DFFR_X1 _221_ (
    .CK(clk),
    .D(b_in[28]),
    .Q(b_q[28]),
    .QN(_109_),
    .RN(rst_n)
  );
  DFFR_X1 _222_ (
    .CK(clk),
    .D(b_in[29]),
    .Q(b_q[29]),
    .QN(_110_),
    .RN(rst_n)
  );
  DFFR_X1 _223_ (
    .CK(clk),
    .D(b_in[30]),
    .Q(b_q[30]),
    .QN(_111_),
    .RN(rst_n)
  );
  DFFR_X1 _224_ (
    .CK(clk),
    .D(b_in[31]),
    .Q(b_q[31]),
    .QN(_047_),
    .RN(rst_n)
  );
endmodule
