/* Generated by Yosys 0.53 (git sha1 53c22ab7c0ced80861c7536c5dae682c30fb5834, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module tc(clk, rst_n, a_in, b_in, y_out);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  input [7:0] a_in;
  wire [7:0] a_in;
  input [7:0] b_in;
  wire [7:0] b_in;
  input clk;
  wire clk;
  wire cmp_eq;
  input rst_n;
  wire rst_n;
  output y_out;
  wire y_out;
  XNOR2_X1 _11_ (
    .A(b_in[5]),
    .B(a_in[5]),
    .ZN(_00_)
  );
  XNOR2_X1 _12_ (
    .A(b_in[6]),
    .B(a_in[6]),
    .ZN(_01_)
  );
  XNOR2_X1 _13_ (
    .A(b_in[1]),
    .B(a_in[1]),
    .ZN(_02_)
  );
  XNOR2_X1 _14_ (
    .A(b_in[7]),
    .B(a_in[7]),
    .ZN(_03_)
  );
  XNOR2_X1 _15_ (
    .A(b_in[0]),
    .B(a_in[0]),
    .ZN(_04_)
  );
  XNOR2_X1 _16_ (
    .A(b_in[4]),
    .B(a_in[4]),
    .ZN(_05_)
  );
  XNOR2_X1 _17_ (
    .A(b_in[2]),
    .B(a_in[2]),
    .ZN(_06_)
  );
  XNOR2_X1 _18_ (
    .A(b_in[3]),
    .B(a_in[3]),
    .ZN(_07_)
  );
  NAND4_X1 _19_ (
    .A1(_00_),
    .A2(_01_),
    .A3(_04_),
    .A4(_05_),
    .ZN(_08_)
  );
  NAND4_X1 _20_ (
    .A1(_02_),
    .A2(_03_),
    .A3(_06_),
    .A4(_07_),
    .ZN(_09_)
  );
  NOR2_X1 _21_ (
    .A1(_08_),
    .A2(_09_),
    .ZN(cmp_eq)
  );
  DFFR_X1 _22_ (
    .CK(clk),
    .D(cmp_eq),
    .Q(y_out),
    .QN(_10_),
    .RN(rst_n)
  );
endmodule
