/* Generated by Yosys 0.53 (git sha1 53c22ab7c0ced80861c7536c5dae682c30fb5834, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module tc(clk, rst_n, a_in, b_in, y_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  input [15:0] a_in;
  wire [15:0] a_in;
  wire [15:0] a_q;
  input [15:0] b_in;
  wire [15:0] b_in;
  wire [15:0] b_q;
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  wire [16:0] y_comb;
  output [16:0] y_out;
  wire [16:0] y_out;
  NAND2_X1 _108_ (
    .A1(a_q[0]),
    .A2(b_q[0]),
    .ZN(_019_)
  );
  NAND2_X1 _109_ (
    .A1(a_q[1]),
    .A2(b_q[1]),
    .ZN(_020_)
  );
  NOR2_X1 _110_ (
    .A1(a_q[1]),
    .A2(b_q[1]),
    .ZN(_021_)
  );
  XOR2_X1 _111_ (
    .A(a_q[1]),
    .B(b_q[1]),
    .Z(_022_)
  );
  XNOR2_X1 _112_ (
    .A(_019_),
    .B(_022_),
    .ZN(y_comb[1])
  );
  OAI21_X1 _113_ (
    .A(_020_),
    .B1(_021_),
    .B2(_019_),
    .ZN(_023_)
  );
  AND2_X1 _114_ (
    .A1(a_q[2]),
    .A2(b_q[2]),
    .ZN(_024_)
  );
  OR2_X1 _115_ (
    .A1(a_q[2]),
    .A2(b_q[2]),
    .ZN(_025_)
  );
  XNOR2_X1 _116_ (
    .A(a_q[2]),
    .B(b_q[2]),
    .ZN(_026_)
  );
  XNOR2_X1 _117_ (
    .A(_023_),
    .B(_026_),
    .ZN(y_comb[2])
  );
  AOI21_X1 _118_ (
    .A(_024_),
    .B1(_025_),
    .B2(_023_),
    .ZN(_027_)
  );
  NAND2_X1 _119_ (
    .A1(a_q[3]),
    .A2(b_q[3]),
    .ZN(_028_)
  );
  NOR2_X1 _120_ (
    .A1(a_q[3]),
    .A2(b_q[3]),
    .ZN(_029_)
  );
  XOR2_X1 _121_ (
    .A(a_q[3]),
    .B(b_q[3]),
    .Z(_030_)
  );
  XNOR2_X1 _122_ (
    .A(_027_),
    .B(_030_),
    .ZN(y_comb[3])
  );
  AND2_X1 _123_ (
    .A1(a_q[4]),
    .A2(b_q[4]),
    .ZN(_031_)
  );
  XNOR2_X1 _124_ (
    .A(a_q[4]),
    .B(b_q[4]),
    .ZN(_032_)
  );
  AOI21_X1 _125_ (
    .A(_029_),
    .B1(_028_),
    .B2(_027_),
    .ZN(_033_)
  );
  AOI211_X1 _126_ (
    .A(_029_),
    .B(_032_),
    .C1(_027_),
    .C2(_028_),
    .ZN(_034_)
  );
  XNOR2_X1 _127_ (
    .A(_032_),
    .B(_033_),
    .ZN(y_comb[4])
  );
  NAND2_X1 _128_ (
    .A1(a_q[5]),
    .A2(b_q[5]),
    .ZN(_035_)
  );
  XOR2_X1 _129_ (
    .A(a_q[5]),
    .B(b_q[5]),
    .Z(_036_)
  );
  OAI21_X1 _130_ (
    .A(_036_),
    .B1(_034_),
    .B2(_031_),
    .ZN(_037_)
  );
  OR3_X1 _131_ (
    .A1(_031_),
    .A2(_034_),
    .A3(_036_),
    .ZN(_038_)
  );
  AND2_X1 _132_ (
    .A1(_037_),
    .A2(_038_),
    .ZN(y_comb[5])
  );
  AND2_X1 _133_ (
    .A1(_035_),
    .A2(_037_),
    .ZN(_039_)
  );
  NAND2_X1 _134_ (
    .A1(a_q[6]),
    .A2(b_q[6]),
    .ZN(_040_)
  );
  XNOR2_X1 _135_ (
    .A(a_q[6]),
    .B(b_q[6]),
    .ZN(_041_)
  );
  XOR2_X1 _136_ (
    .A(_039_),
    .B(_041_),
    .Z(y_comb[6])
  );
  OAI21_X1 _137_ (
    .A(_040_),
    .B1(_041_),
    .B2(_039_),
    .ZN(_042_)
  );
  AND2_X1 _138_ (
    .A1(a_q[7]),
    .A2(b_q[7]),
    .ZN(_043_)
  );
  OR2_X1 _139_ (
    .A1(a_q[7]),
    .A2(b_q[7]),
    .ZN(_044_)
  );
  XNOR2_X1 _140_ (
    .A(a_q[7]),
    .B(b_q[7]),
    .ZN(_045_)
  );
  XNOR2_X1 _141_ (
    .A(_042_),
    .B(_045_),
    .ZN(y_comb[7])
  );
  NAND2_X1 _142_ (
    .A1(a_q[8]),
    .A2(b_q[8]),
    .ZN(_046_)
  );
  XOR2_X1 _143_ (
    .A(a_q[8]),
    .B(b_q[8]),
    .Z(_047_)
  );
  OAI21_X1 _144_ (
    .A(_044_),
    .B1(_043_),
    .B2(_042_),
    .ZN(_048_)
  );
  OAI211_X1 _145_ (
    .A(_044_),
    .B(_047_),
    .C1(_042_),
    .C2(_043_),
    .ZN(_049_)
  );
  XNOR2_X1 _146_ (
    .A(_047_),
    .B(_048_),
    .ZN(y_comb[8])
  );
  NAND2_X1 _147_ (
    .A1(_046_),
    .A2(_049_),
    .ZN(_050_)
  );
  AND2_X1 _148_ (
    .A1(a_q[9]),
    .A2(b_q[9]),
    .ZN(_051_)
  );
  NOR2_X1 _149_ (
    .A1(a_q[9]),
    .A2(b_q[9]),
    .ZN(_052_)
  );
  OR2_X1 _150_ (
    .A1(_051_),
    .A2(_052_),
    .ZN(_053_)
  );
  XNOR2_X1 _151_ (
    .A(_050_),
    .B(_053_),
    .ZN(y_comb[9])
  );
  NAND2_X1 _152_ (
    .A1(a_q[10]),
    .A2(b_q[10]),
    .ZN(_054_)
  );
  XOR2_X1 _153_ (
    .A(a_q[10]),
    .B(b_q[10]),
    .Z(_055_)
  );
  AOI21_X1 _154_ (
    .A(_052_),
    .B1(_049_),
    .B2(_046_),
    .ZN(_056_)
  );
  OAI21_X1 _155_ (
    .A(_055_),
    .B1(_056_),
    .B2(_051_),
    .ZN(_057_)
  );
  OR3_X1 _156_ (
    .A1(_051_),
    .A2(_055_),
    .A3(_056_),
    .ZN(_058_)
  );
  AND2_X1 _157_ (
    .A1(_057_),
    .A2(_058_),
    .ZN(y_comb[10])
  );
  NAND2_X1 _158_ (
    .A1(_054_),
    .A2(_057_),
    .ZN(_000_)
  );
  NAND2_X1 _159_ (
    .A1(a_q[11]),
    .A2(b_q[11]),
    .ZN(_001_)
  );
  OR2_X1 _160_ (
    .A1(a_q[11]),
    .A2(b_q[11]),
    .ZN(_002_)
  );
  NAND2_X1 _161_ (
    .A1(_001_),
    .A2(_002_),
    .ZN(_003_)
  );
  XNOR2_X1 _162_ (
    .A(_000_),
    .B(_003_),
    .ZN(y_comb[11])
  );
  AND2_X1 _163_ (
    .A1(a_q[12]),
    .A2(b_q[12]),
    .ZN(_004_)
  );
  XOR2_X1 _164_ (
    .A(a_q[12]),
    .B(b_q[12]),
    .Z(_005_)
  );
  NAND3_X1 _165_ (
    .A1(_054_),
    .A2(_057_),
    .A3(_001_),
    .ZN(_006_)
  );
  AND2_X1 _166_ (
    .A1(_002_),
    .A2(_006_),
    .ZN(_007_)
  );
  XOR2_X1 _167_ (
    .A(_005_),
    .B(_007_),
    .Z(y_comb[12])
  );
  AOI21_X1 _168_ (
    .A(_004_),
    .B1(_005_),
    .B2(_007_),
    .ZN(_008_)
  );
  NAND2_X1 _169_ (
    .A1(a_q[13]),
    .A2(b_q[13]),
    .ZN(_009_)
  );
  NOR2_X1 _170_ (
    .A1(a_q[13]),
    .A2(b_q[13]),
    .ZN(_010_)
  );
  XOR2_X1 _171_ (
    .A(a_q[13]),
    .B(b_q[13]),
    .Z(_011_)
  );
  XNOR2_X1 _172_ (
    .A(_008_),
    .B(_011_),
    .ZN(y_comb[13])
  );
  AND2_X1 _173_ (
    .A1(a_q[14]),
    .A2(b_q[14]),
    .ZN(_012_)
  );
  XOR2_X1 _174_ (
    .A(a_q[14]),
    .B(b_q[14]),
    .Z(_013_)
  );
  OAI21_X1 _175_ (
    .A(_009_),
    .B1(_010_),
    .B2(_008_),
    .ZN(_014_)
  );
  XOR2_X1 _176_ (
    .A(_013_),
    .B(_014_),
    .Z(y_comb[14])
  );
  AOI21_X1 _177_ (
    .A(_012_),
    .B1(_013_),
    .B2(_014_),
    .ZN(_015_)
  );
  NAND2_X1 _178_ (
    .A1(a_q[15]),
    .A2(b_q[15]),
    .ZN(_016_)
  );
  NOR2_X1 _179_ (
    .A1(a_q[15]),
    .A2(b_q[15]),
    .ZN(_017_)
  );
  XOR2_X1 _180_ (
    .A(a_q[15]),
    .B(b_q[15]),
    .Z(_018_)
  );
  XNOR2_X1 _181_ (
    .A(_015_),
    .B(_018_),
    .ZN(y_comb[15])
  );
  XOR2_X1 _182_ (
    .A(a_q[0]),
    .B(b_q[0]),
    .Z(y_comb[0])
  );
  OAI21_X1 _183_ (
    .A(_016_),
    .B1(_017_),
    .B2(_015_),
    .ZN(y_comb[16])
  );
  DFFR_X1 _184_ (
    .CK(clk),
    .D(y_comb[0]),
    .Q(y_out[0]),
    .QN(_060_),
    .RN(rst_n)
  );
  DFFR_X1 _185_ (
    .CK(clk),
    .D(y_comb[1]),
    .Q(y_out[1]),
    .QN(_061_),
    .RN(rst_n)
  );
  DFFR_X1 _186_ (
    .CK(clk),
    .D(y_comb[2]),
    .Q(y_out[2]),
    .QN(_062_),
    .RN(rst_n)
  );
  DFFR_X1 _187_ (
    .CK(clk),
    .D(y_comb[3]),
    .Q(y_out[3]),
    .QN(_063_),
    .RN(rst_n)
  );
  DFFR_X1 _188_ (
    .CK(clk),
    .D(y_comb[4]),
    .Q(y_out[4]),
    .QN(_064_),
    .RN(rst_n)
  );
  DFFR_X1 _189_ (
    .CK(clk),
    .D(y_comb[5]),
    .Q(y_out[5]),
    .QN(_065_),
    .RN(rst_n)
  );
  DFFR_X1 _190_ (
    .CK(clk),
    .D(y_comb[6]),
    .Q(y_out[6]),
    .QN(_066_),
    .RN(rst_n)
  );
  DFFR_X1 _191_ (
    .CK(clk),
    .D(y_comb[7]),
    .Q(y_out[7]),
    .QN(_067_),
    .RN(rst_n)
  );
  DFFR_X1 _192_ (
    .CK(clk),
    .D(y_comb[8]),
    .Q(y_out[8]),
    .QN(_068_),
    .RN(rst_n)
  );
  DFFR_X1 _193_ (
    .CK(clk),
    .D(y_comb[9]),
    .Q(y_out[9]),
    .QN(_069_),
    .RN(rst_n)
  );
  DFFR_X1 _194_ (
    .CK(clk),
    .D(y_comb[10]),
    .Q(y_out[10]),
    .QN(_070_),
    .RN(rst_n)
  );
  DFFR_X1 _195_ (
    .CK(clk),
    .D(y_comb[11]),
    .Q(y_out[11]),
    .QN(_071_),
    .RN(rst_n)
  );
  DFFR_X1 _196_ (
    .CK(clk),
    .D(y_comb[12]),
    .Q(y_out[12]),
    .QN(_072_),
    .RN(rst_n)
  );
  DFFR_X1 _197_ (
    .CK(clk),
    .D(y_comb[13]),
    .Q(y_out[13]),
    .QN(_073_),
    .RN(rst_n)
  );
  DFFR_X1 _198_ (
    .CK(clk),
    .D(y_comb[14]),
    .Q(y_out[14]),
    .QN(_074_),
    .RN(rst_n)
  );
  DFFR_X1 _199_ (
    .CK(clk),
    .D(y_comb[15]),
    .Q(y_out[15]),
    .QN(_075_),
    .RN(rst_n)
  );
  DFFR_X1 _200_ (
    .CK(clk),
    .D(y_comb[16]),
    .Q(y_out[16]),
    .QN(_076_),
    .RN(rst_n)
  );
  DFFR_X1 _201_ (
    .CK(clk),
    .D(a_in[0]),
    .Q(a_q[0]),
    .QN(_077_),
    .RN(rst_n)
  );
  DFFR_X1 _202_ (
    .CK(clk),
    .D(a_in[1]),
    .Q(a_q[1]),
    .QN(_078_),
    .RN(rst_n)
  );
  DFFR_X1 _203_ (
    .CK(clk),
    .D(a_in[2]),
    .Q(a_q[2]),
    .QN(_079_),
    .RN(rst_n)
  );
  DFFR_X1 _204_ (
    .CK(clk),
    .D(a_in[3]),
    .Q(a_q[3]),
    .QN(_080_),
    .RN(rst_n)
  );
  DFFR_X1 _205_ (
    .CK(clk),
    .D(a_in[4]),
    .Q(a_q[4]),
    .QN(_081_),
    .RN(rst_n)
  );
  DFFR_X1 _206_ (
    .CK(clk),
    .D(a_in[5]),
    .Q(a_q[5]),
    .QN(_082_),
    .RN(rst_n)
  );
  DFFR_X1 _207_ (
    .CK(clk),
    .D(a_in[6]),
    .Q(a_q[6]),
    .QN(_083_),
    .RN(rst_n)
  );
  DFFR_X1 _208_ (
    .CK(clk),
    .D(a_in[7]),
    .Q(a_q[7]),
    .QN(_084_),
    .RN(rst_n)
  );
  DFFR_X1 _209_ (
    .CK(clk),
    .D(a_in[8]),
    .Q(a_q[8]),
    .QN(_085_),
    .RN(rst_n)
  );
  DFFR_X1 _210_ (
    .CK(clk),
    .D(a_in[9]),
    .Q(a_q[9]),
    .QN(_086_),
    .RN(rst_n)
  );
  DFFR_X1 _211_ (
    .CK(clk),
    .D(a_in[10]),
    .Q(a_q[10]),
    .QN(_087_),
    .RN(rst_n)
  );
  DFFR_X1 _212_ (
    .CK(clk),
    .D(a_in[11]),
    .Q(a_q[11]),
    .QN(_088_),
    .RN(rst_n)
  );
  DFFR_X1 _213_ (
    .CK(clk),
    .D(a_in[12]),
    .Q(a_q[12]),
    .QN(_089_),
    .RN(rst_n)
  );
  DFFR_X1 _214_ (
    .CK(clk),
    .D(a_in[13]),
    .Q(a_q[13]),
    .QN(_090_),
    .RN(rst_n)
  );
  DFFR_X1 _215_ (
    .CK(clk),
    .D(a_in[14]),
    .Q(a_q[14]),
    .QN(_091_),
    .RN(rst_n)
  );
  DFFR_X1 _216_ (
    .CK(clk),
    .D(a_in[15]),
    .Q(a_q[15]),
    .QN(_092_),
    .RN(rst_n)
  );
  DFFR_X1 _217_ (
    .CK(clk),
    .D(b_in[0]),
    .Q(b_q[0]),
    .QN(_093_),
    .RN(rst_n)
  );
  DFFR_X1 _218_ (
    .CK(clk),
    .D(b_in[1]),
    .Q(b_q[1]),
    .QN(_094_),
    .RN(rst_n)
  );
  DFFR_X1 _219_ (
    .CK(clk),
    .D(b_in[2]),
    .Q(b_q[2]),
    .QN(_095_),
    .RN(rst_n)
  );
  DFFR_X1 _220_ (
    .CK(clk),
    .D(b_in[3]),
    .Q(b_q[3]),
    .QN(_096_),
    .RN(rst_n)
  );
  DFFR_X1 _221_ (
    .CK(clk),
    .D(b_in[4]),
    .Q(b_q[4]),
    .QN(_097_),
    .RN(rst_n)
  );
  DFFR_X1 _222_ (
    .CK(clk),
    .D(b_in[5]),
    .Q(b_q[5]),
    .QN(_098_),
    .RN(rst_n)
  );
  DFFR_X1 _223_ (
    .CK(clk),
    .D(b_in[6]),
    .Q(b_q[6]),
    .QN(_099_),
    .RN(rst_n)
  );
  DFFR_X1 _224_ (
    .CK(clk),
    .D(b_in[7]),
    .Q(b_q[7]),
    .QN(_100_),
    .RN(rst_n)
  );
  DFFR_X1 _225_ (
    .CK(clk),
    .D(b_in[8]),
    .Q(b_q[8]),
    .QN(_101_),
    .RN(rst_n)
  );
  DFFR_X1 _226_ (
    .CK(clk),
    .D(b_in[9]),
    .Q(b_q[9]),
    .QN(_102_),
    .RN(rst_n)
  );
  DFFR_X1 _227_ (
    .CK(clk),
    .D(b_in[10]),
    .Q(b_q[10]),
    .QN(_103_),
    .RN(rst_n)
  );
  DFFR_X1 _228_ (
    .CK(clk),
    .D(b_in[11]),
    .Q(b_q[11]),
    .QN(_104_),
    .RN(rst_n)
  );
  DFFR_X1 _229_ (
    .CK(clk),
    .D(b_in[12]),
    .Q(b_q[12]),
    .QN(_105_),
    .RN(rst_n)
  );
  DFFR_X1 _230_ (
    .CK(clk),
    .D(b_in[13]),
    .Q(b_q[13]),
    .QN(_106_),
    .RN(rst_n)
  );
  DFFR_X1 _231_ (
    .CK(clk),
    .D(b_in[14]),
    .Q(b_q[14]),
    .QN(_107_),
    .RN(rst_n)
  );
  DFFR_X1 _232_ (
    .CK(clk),
    .D(b_in[15]),
    .Q(b_q[15]),
    .QN(_059_),
    .RN(rst_n)
  );
endmodule
